export const ADDITIONAL_EXAM_EN=[
['养老金沟通',`When an employer replaces a guaranteed retirement benefit with a scheme based on individual savings, the change is often presented as an expansion of choice. Employees can select among investment funds and adjust contributions to their circumstances. Yet choice is not the only thing being transferred. Under the old arrangement, the employer bore much of the risk that assets would fail to deliver the promised benefit. Under the new one, that uncertainty is carried more directly by the worker, even if the employer continues to contribute.

This distinction is easily obscured by examples showing what a steady contribution might produce over several decades. Such illustrations require assumptions about investment returns, fees, inflation and the pattern of employment. A small difference in annual charges can have a large cumulative effect, while a period without paid work may interrupt contributions at precisely the time a household has few resources to spare. A projected balance is therefore not a promise, and a range of outcomes is more informative than a single attractive number.

Providing a longer information booklet is not necessarily the solution. People vary in their ability and willingness to compare unfamiliar financial products, especially when the consequences lie far in the future. Some employers respond by choosing a default fund for anyone who makes no active selection. A default can protect workers from accidental non-participation, but it also gives its designers considerable influence. The criteria used to select it should be open to scrutiny, including whether charges reward the provider for services that members actually need.

There is also a difference between explaining a product and enabling a decision. An employee approaching retirement may need to understand how income will be affected by withdrawing money during a market decline. A younger worker may be more concerned about carrying savings between employers. Treating both as recipients of the same generic message can satisfy a formal disclosure requirement without resolving either person's practical question.

None of this establishes that individual savings arrangements are always inferior to guaranteed benefits. The latter also depend on funding, governance and the ability of institutions to meet commitments. The point is that comparisons should make the allocation of risk explicit. More options do not automatically mean greater security, and an apparently low contribution today may imply a less predictable income tomorrow. Responsible communication should distinguish what is guaranteed, what is estimated and what the employee must decide. It should also explain where independent guidance is available, rather than using uncertainty as an opportunity to steer workers towards the most profitable option for the seller. A meaningful exercise of choice requires enough clarity to recognise the limits of one's own knowledge and enough time to seek help before an irreversible decision is made.`,
'当雇主将保证退休待遇的制度改为基于个人储蓄的方案时，这一变化常被描述为扩大选择。员工可以选择投资基金，并根据自身情况调整缴费。然而，被转移的不只是选择权。在原有安排下，资产无法兑现承诺待遇的风险主要由雇主承担。在新安排下，即使雇主继续缴费，这种不确定性也更直接地由劳动者承担。\n\n展示稳定缴费数十年后可能获得多少收益的例子，很容易掩盖这一区别。这类示例需要对投资回报、费用、通胀和就业轨迹作出假设。年度收费的微小差异可能产生很大的累积影响，而没有有薪工作的时期可能恰好在家庭资源最紧张时打断缴费。因此，预计余额并非承诺，相比一个诱人的数字，一系列可能结果更有信息价值。\n\n提供更长的说明手册未必能解决问题。人们比较陌生金融产品的能力和意愿各不相同，尤其是当后果多年后才会显现时。一些雇主为没有主动选择的人设置默认基金。默认选项可以避免劳动者意外未参保，却也使设计者拥有相当大的影响力。选择标准应接受审查，包括收费是否是对成员真正需要的服务的报酬。\n\n解释产品与帮助作出决定也有所不同。临近退休的员工可能需要了解在市场下跌时提款会怎样影响收入；年轻劳动者可能更关心换雇主时如何转移储蓄。向两者提供同样的通用信息，可能满足正式披露要求，却没有解决任何一方的实际问题。\n\n这些都不能证明个人储蓄方案总是不如保证待遇的制度。后者也依赖资金、治理以及机构兑现承诺的能力。关键在于比较应明确风险分配。更多选项不自动意味着更高保障，今天看似较低的缴费可能意味着明天更难预测的收入。负责任的沟通应区分哪些是保证、哪些是估计、哪些需要员工决定，还应说明哪里可以获得独立指导，而不是利用不确定性将劳动者引向对销售者最有利的选项。有意义的选择需要足够清晰的信息，使人认识到自身知识的局限，也需要足够时间，在作出不可逆决定前寻求帮助。'],
['农业育种与种子保存',`The value of a seed collection is often expressed as the number of varieties it contains. That figure matters, but it says little about whether the collection can support farming under changing conditions. Seeds must remain viable, their characteristics need to be documented, and researchers must be able to connect a sample with reliable information about where it came from. A freezer full of poorly described material is not the same as a usable resource.

Maintaining a collection is consequently an active process. Some seeds need to be grown periodically so that fresh supplies can be harvested. During this regeneration, accidental mixing or selection can alter what is being preserved. Staff must therefore pay attention not only to storage temperatures but also to the conditions under which plants are reproduced. The less visible work of maintaining records and checking identity can be as important as acquiring a rare new sample.

Farmers hold another kind of knowledge. They may know how a local variety performs on a particular soil, when its grain can be stored safely or why households prefer it despite a lower yield. Such information does not always fit the categories used in a laboratory database. If it is omitted, a breeder may overlook characteristics that matter to people who will eventually grow or consume the crop. Collaboration requires more than extracting observations: contributors need to understand how their knowledge will be used and how benefits from resulting innovations will be shared.

Climate change adds urgency without providing a simple ranking of which material should be saved first. A variety that tolerates drought may be vulnerable to a disease expected to spread as temperatures rise. A high-yielding crop under carefully controlled conditions may perform less reliably where fertiliser is expensive or rainfall unpredictable. Diversity is valuable partly because future needs cannot be specified with confidence. Preserving several alternatives is not necessarily an inefficient duplication of effort.

The challenge for funders is that successful conservation may have no dramatic short-term outcome. Its contribution becomes visible when a breeder needs a trait that would otherwise have disappeared, or when a community seeks to restore a crop no longer widely cultivated. Funding tied only to annual acquisitions can encourage institutions to collect more than they can maintain responsibly. A better assessment would examine viability, documentation, access and the quality of partnerships alongside the size of the collection. It would also recognise that a central facility and cultivation in farmers' fields serve related but different purposes. The former can provide a safeguard against loss; the latter allows crops and practical knowledge to continue developing under local conditions. Neither can simply replace the other, and treating them as competing investments may weaken the overall system.`,
'种子收藏的价值常用所含品种数量表示。这个数字固然重要，却几乎不能说明该收藏能否支持不断变化条件下的农业。种子必须保持活力，其特征需要记录，研究者还必须能够将样本与可靠的来源信息联系起来。装满描述不清材料的冷库，并不等于可利用的资源。\n\n因此，维护收藏是一个主动过程。一些种子需要定期种植，以收获新的种子。在这种繁殖更新过程中，意外混杂或选择可能改变原本要保存的材料。所以，工作人员不仅要关注储存温度，还要关注植物繁殖的条件。维护记录和核对身份这类不显眼的工作，可能与获取稀有新样本同样重要。\n\n农民掌握另一类知识。他们可能知道地方品种在某种土壤上的表现、谷物何时能够安全储存，或者为何产量较低却仍受家庭喜爱。这些信息不一定适合实验室数据库的分类。如果遗漏，育种者可能忽视最终种植或食用作物的人所重视的特征。合作不只是提取观察资料：贡献者需要了解其知识将如何使用，以及由此产生的创新收益将如何分享。\n\n气候变化增加了紧迫性，却无法提供应先保存哪些材料的简单排序。耐旱品种可能易受预计随气温升高而传播的某种疾病侵袭。精细控制条件下的高产作物，在化肥昂贵或降雨不可预测的地方可能表现不够稳定。多样性之所以有价值，部分原因是未来需求无法确定。保存多种替代方案并不一定是低效重复。\n\n资助者面临的挑战在于，成功保存可能没有显著的短期成果。只有当育种者需要一个否则会消失的性状，或社区希望恢复不再广泛种植的作物时，其贡献才会显现。只与年度收集量挂钩的资金，可能鼓励机构收集超出其负责任维护能力的材料。更好的评估应在考察数量之外，也考察活力、文档、获取途径和合作质量；还应认识到集中设施与农田种植承担相互关联但不同的作用。前者防止材料丢失，后者使作物与实践知识继续在地方条件下发展。两者不能简单互相替代，将其视为竞争性投资可能削弱整个系统。']
];

