export const REBUILD_EN=[
['商业新闻与订阅',`The decision of a regional newspaper to abandon advertising in favour of subscriptions was welcomed by readers who believed that payment would insulate journalism from commercial pressure. Their confidence was understandable. Under the previous arrangement, an investigation into a major employer could threaten revenue even before anyone had attempted to influence its conclusions. Replacing advertisers with subscribers appeared to remove that particular conflict. It did not, however, remove the need to decide whose preferences should count.

Within months, the newsroom discovered that its most reliable subscribers were concentrated in prosperous neighbourhoods. Reports on housing conditions elsewhere attracted considerable attention but relatively few new payments. A dashboard designed to show which articles converted visitors into subscribers therefore rewarded some subjects more consistently than others. No proprietor had instructed reporters to neglect poorer districts. Nevertheless, a measure introduced to support editorial independence was beginning to narrow the definition of the public whom the newspaper served.

Editors could have ignored the dashboard, but this would not have made salaries or printing costs disappear. Instead, they separated commercial targets from the allocation of a protected reporting budget. Subscription income helped finance investigations whose value would be assessed through documented public consequences rather than immediate sales. The distinction was imperfect: an investigation that prompted an official inquiry might still fail to reach residents with limited internet access. The newspaper consequently maintained a printed bulletin distributed through libraries and community organisations.

These measures attracted criticism from subscribers who felt they were paying for coverage intended primarily for other people. The editors replied that purchasing access did not confer ownership of the editorial agenda. That response would have sounded hollow had the newspaper refused to explain its priorities. It therefore published accounts showing the cost of major investigations and the reasons for pursuing them, while withholding details that might identify confidential sources. Transparency, in this context, meant making resource decisions open to scrutiny, not exposing every step of reporting to a public vote.

The experiment illustrates a difficulty often obscured by the distinction between commercial and independent media. Every funding arrangement distributes influence, even when no individual donor or advertiser can dictate a story. A subscription model may strengthen journalism, but it cannot by itself establish the boundaries of a newspaper's responsibility. Those boundaries must remain contestable, particularly by people whose inability to pay would otherwise render their interests invisible. Financial survival is a necessary condition of sustained reporting; it is not a complete account of what that reporting is for. Nor can the volume of online reaction settle the question, since the communities most affected by an investigation may be the least equipped to make their response visible through digital metrics.`, `一家地方报纸决定放弃广告收入、转向订阅收费，认为付费能够使新闻免受商业压力的读者对此表示欢迎。他们的信心不难理解。在原有模式下，对一家主要雇主的调查，甚至在任何人试图干预结论之前，就可能威胁报纸的收入。以订户取代广告主，似乎消除了这一特定冲突，但并未消除另一个问题：应当重视谁的偏好。

几个月后，编辑部发现最稳定的订户集中在富裕社区。关于其他地区住房条件的报道虽受到关注，却很少带来新增付费。用来显示哪些文章能促使访客订阅的数据看板，因此总是更有利于某些选题。没有报业老板命令记者忽略贫困地区，然而，一项旨在支持编辑独立的指标，正逐渐缩小报纸所服务公众的范围。

编辑可以忽视看板，但工资和印刷费用并不会因此消失。他们选择把商业目标与一笔受到保护的报道预算分开。订阅收入资助调查报道，后者的价值依据有记录的公共影响、而非即时销量来评估。这种区分并不完美：促成官方调查的报道，仍可能无法触达上网不便的居民。因此，报纸继续通过图书馆和社区组织分发印刷简报。

这些措施遭到一些订户批评，他们认为自己在为主要面向别人的报道付费。编辑回应说，购买阅读权限并不意味着拥有决定编辑议程的权利。如果报纸拒绝解释自身的优先事项，这种回应便会显得空洞。因此，它公布主要调查的成本及开展理由，同时隐去可能暴露秘密消息来源的细节。这里的透明意味着资源决策可受审查，而不是让报道的每个步骤都接受公众投票。

这一尝试说明了商业媒体与独立媒体的二分法常常掩盖的难题。即使单个捐赠者或广告主无法指定报道，每种筹资安排仍会分配影响力。订阅制可能加强新闻业，却不能自行划定报纸责任的边界。这些边界必须容许质疑，特别是要让那些无力付费、利益可能因此被忽视的人参与。财务生存是持续报道的必要条件，却不能完整说明报道的目的。网络反应的数量也无法解决这个问题，因为受调查报道影响最大的群体，可能最缺乏通过数字指标让自己的回应被看见的条件。`, '订阅独立与议程控制；necessary condition 限定；whose、had倒装反事实；not…but透明度范围。'],
['药物试验与代表性',`A treatment can succeed in a clinical trial without settling the question of how it should be used outside it. Participants are often selected partly because they are likely to follow a demanding schedule of visits and tests. That choice improves the reliability of measurements, but may leave out people whose health problems are complicated by unstable housing, caring responsibilities or the use of several other medicines. The resulting evidence is not worthless; its limits simply form part of what a decision maker needs to know.

Consider a trial in which the treatment group experiences fewer hospital admissions than the comparison group. The difference may be clinically important. Yet translating it into an estimate of savings requires assumptions about local practice, the cost of monitoring and whether patients can actually obtain the treatment. A reduction observed among closely supervised volunteers cannot automatically be treated as the reduction a health service will achieve across its entire population. Nor does a statistically convincing average establish that every subgroup benefits equally.

One response is to demand broader participation before approving any new treatment. This can improve representativeness, but it also involves trade-offs. Recruiting people with varied circumstances takes time, and additional safeguards may be needed for those who face greater risks. Delaying access while evidence is gathered can itself have consequences for patients without satisfactory alternatives. The choice is therefore not between certainty and recklessness. It is between different ways of distributing uncertainty, costs and opportunities while the evidence develops.

Conditional approval offers one possible arrangement, provided that the conditions are more than promises. Authorities may require continued data collection, specify outcomes that would trigger a review and reserve the right to restrict use if expected benefits fail to materialise. Such arrangements depend on institutions being able to collect relevant information after the publicity surrounding a launch has faded. If follow-up studies repeatedly arrive late, provisional access can quietly become permanent access without the intended learning ever taking place.

Patients should consequently be told not only what a trial found but also which questions remain open. This does not require presenting every technical limitation as a reason for alarm. It requires distinguishing an observed result from an extrapolation, and a justified hope from a guarantee. A clear explanation may sometimes sound less reassuring than a simple claim of effectiveness. In the longer term, however, it gives patients and clinicians a basis for revising decisions when experience differs from expectations, rather than forcing them to choose between unquestioning trust and complete rejection of the original evidence. This distinction is especially important when early publicity has encouraged people to interpret regulatory permission as confirmation that the same benefits will follow under all conditions.`, `一种治疗在临床试验中取得成功，并不意味着如何在试验外使用它的问题已经解决。筛选参与者的一个依据，往往是他们能否遵守严格的复诊和检测安排。这提高了测量的可靠性，却可能排除那些因住房不稳定、照护责任或同时服用多种药物而使健康状况更加复杂的人。所得证据并非毫无价值，只是其局限也属于决策者需要了解的内容。

假设试验中治疗组住院次数少于对照组，这一差异可能具有重要临床意义，但把它换算成节省费用的估计，必须对当地诊疗方式、监测成本以及患者能否真正获得治疗作出假设。在受到密切监督的志愿者中观察到的降幅，不能自动当作医疗系统在全部人群中能够实现的降幅。统计上令人信服的平均结果，也不能证明每个亚组同等受益。

一种应对办法是在批准任何新治疗之前要求更广泛的参与。这有助于提高代表性，却也涉及取舍。招募处境不同的人需要时间，对于风险较高者还可能需要额外保护。在收集证据期间延迟准入，本身也可能影响缺乏满意替代方案的患者。因此，选择并非在确定性与鲁莽之间，而是在证据不断发展的过程中，以不同方式分配不确定性、成本与机会。

有条件批准提供了一种安排，前提是条件不只是承诺。监管部门可以要求持续收集数据，规定哪些结果应触发复审，并保留在预期收益未实现时限制使用的权利。这取决于机构能否在上市宣传消退之后继续收集相关信息。如果后续研究一再迟到，临时准入可能悄然变成永久准入，却始终未实现原定的知识积累。

因此，患者不仅应被告知试验发现，还应了解哪些问题仍未解决。这不意味着把每一项技术局限都说成值得恐慌的理由，而是要区分观察结果与外推、合理希望与保证。清楚的解释有时不如简单宣称有效那样令人安心；但长期来看，它为患者和临床医生在实际经验偏离预期时调整决定提供依据，而不必在无条件信任与全盘否定最初证据之间选择。当早期宣传使人们把监管许可理解为任何条件下都能获得同样收益的确认时，这一区分尤其重要。`, '试验内外效度；statistically convincing与临床/经济结果区分；反事实限制和conditional approval。'],
['历史地图与边界',`Historical maps have acquired an authority their makers would sometimes have found surprising. Displayed in a museum or reproduced in a legal submission, a coloured line can appear to offer precise evidence of a boundary. Yet the original document may have been prepared to estimate tax revenue, advertise a proposed railway or describe territory that no surveyor had visited. What looks like a geographical fact may therefore be a statement about an institution's ambitions, assumptions or practical needs.

This does not make maps useless as evidence. It makes their purposes relevant to interpretation. A historian comparing two maps must ask whether apparent changes reflect events on the ground or differences in scale, classification and access to information. A settlement absent from one map may have been too small to include, considered politically unimportant or known under a name the researcher has not recognised. Absence alone does not establish that the settlement did not exist. Equally, the presence of a carefully printed label does not prove that an authority exercised effective control there.

Digitisation can intensify these difficulties while appearing to resolve them. When an old map is aligned with modern coordinates, users can zoom into an image with a precision unavailable to its creator. The software may place every point consistently, but that consistency belongs to the transformation, not necessarily to the original observations. An elegant interface can conceal uncertainty more successfully than a visibly rough sketch. Researchers should therefore preserve information about distortions rather than treating successful alignment as independent confirmation of accuracy.

Local testimony provides another perspective, though it too requires scrutiny. Memories of paths, seasonal grazing and shared wells may reveal patterns of use that administrative maps omitted. Those memories can also be shaped by later disputes. Treating official documents as automatically superior would reproduce the exclusions of the archive; treating every recollection as equally conclusive would abandon the task of evaluating evidence. The challenge is to explain how different sources support, qualify or contradict a particular claim without pretending that they all answer the same question.

For institutions exhibiting disputed maps, acknowledging these limits need not mean taking no position. A display can identify what is firmly documented, distinguish it from inference and show where interpretations diverge. Such an approach asks visitors to do more than admire an apparently definitive picture of the past. It invites them to examine how geographical knowledge was produced and why some ways of representing space became authoritative while others remained difficult to see. The result may be a less tidy narrative, but it is also one less likely to mistake the survival of a document for proof that its categories were universally accepted.`, `历史地图如今获得的权威，有时连其制作者也会感到意外。在博物馆展示或法律文件引用中，一条彩色线条似乎能够为边界提供精确证据。然而，原始文件可能是为估计税收、宣传拟建铁路，或描述测量者从未到访的地域而制作。因此，看似地理事实的内容，也可能表达的是一个机构的抱负、假设或实际需要。

这并不使地图失去证据价值，而是说明解释时应考虑其用途。比较两幅地图的历史学者必须追问：表面变化反映的是实地事件，还是比例尺、分类方式与信息来源的差异？某个聚落未出现在一幅地图上，可能是太小而被省略、被认为政治上不重要，或使用了研究者未能识别的名字。仅凭缺失不能证明聚落不存在。同样，一个精心印制的地名，也不能证明某个当局在那里实行了有效控制。

数字化看似解决问题，却可能加剧这些困难。旧地图与现代坐标对齐后，用户可以用制作者不曾拥有的精度放大图像。软件或许能够一致地定位每个点，但这种一致性属于转换过程，不一定属于原始观测。精美界面可能比明显粗糙的草图更成功地掩盖不确定性。因此，研究人员应保留失真信息，而不能把成功对齐当作准确性的独立证明。

地方证言提供了另一个视角，但同样需要审查。关于小路、季节性放牧和共有水井的记忆，可能揭示行政地图遗漏的使用方式，也可能受到后来争端的影响。把官方文书自动视为更优，会重现档案的排斥；把每段回忆都视为同样足以定论，则意味着放弃评估证据。难点在于说明不同来源如何支持、限定或反驳特定主张，而不假装它们都在回答同一问题。

展示争议地图的机构承认这些局限，并不意味着不持任何立场。展览可以指出哪些内容证据确凿，将其与推断区分，并展示解释的分歧。这样做要求参观者不只是欣赏一幅看似确定的历史图景，而是考察地理知识如何产生，以及为何某些空间呈现方式获得权威、其他方式却难以被看见。结果或许不那么整齐，却也更不容易把文献留存误认为其中分类曾被普遍接受的证明。`, '地图的证明力、缺失证据与不存在；数字配准精度不等于史料准确；whose/what关系结构。'],
['货币联盟与调整',`A common currency removes one conspicuous source of uncertainty for firms trading across borders: they no longer need to predict movements between the currencies of participating countries. It does not remove differences in productivity, credit conditions or the capacity of governments to respond to a downturn. Indeed, the disappearance of exchange-rate movements may make those differences harder to recognise until they have produced substantial imbalances. Stability in one price should not be confused with stability in the system as a whole.

Suppose a region loses export demand while others continue to expand. With a separate currency, depreciation might help its producers regain competitiveness, although the higher cost of imports would impose losses on consumers. Within a monetary union, that route is unavailable. Adjustment must occur through wages, prices, migration, fiscal transfers or some combination of them. Each mechanism distributes the burden differently. Migration can reduce unemployment in the affected region while weakening its tax base and separating families; wage restraint may preserve jobs but prolong weak domestic demand.

It is tempting to describe these consequences as evidence that the currency union was simply a mistake. Such a judgment overlooks the costs and risks of the alternatives. Small economies with independent currencies may face volatile capital flows and expensive borrowing even when their domestic policies are prudent. The relevant comparison is not between an imperfect union and a frictionless national economy. It is between institutional arrangements that expose people to different kinds of instability and provide different means of sharing its costs.

This is why the design of common financial institutions matters. A mechanism that lends only after a government has exhausted its resources may arrive too late to prevent a local contraction from spreading. Yet transfers without credible rules can undermine political support in countries expected to contribute. Resolving the tension requires more than choosing a larger fund. Participants must agree on what counts as an exceptional shock, which obligations accompany assistance and how temporary support will be distinguished from a permanent transfer of responsibility.

Public debate often treats such details as technical matters best left to specialists. In fact, they determine whose losses will be recognised and whose will be treated as the unavoidable consequence of competition. A durable monetary arrangement requires citizens to understand these choices well enough to contest them. Otherwise, rules presented as neutral constraints may lose legitimacy precisely when they are most needed, leaving governments to improvise under pressure and encouraging each electorate to believe that the others have benefited at its expense. The promise of predictability then becomes dependent on political relationships that the economic design had assumed, rather than helped to sustain.`, `共同货币消除了跨境经营企业面临的一项显著不确定性：不必再预测成员国货币之间的汇率变化。但它并未消除生产率、信贷条件或政府应对衰退能力的差异。事实上，汇率变动的消失可能使这些差异更难被识别，直到其造成严重失衡。某一种价格稳定，不应与整个系统稳定混为一谈。

假设某地区出口需求下降，而其他地区继续扩张。若有独立货币，贬值可能帮助生产者恢复竞争力，尽管进口成本上涨会使消费者受损。在货币联盟内，这条路径不可行。调整必须通过工资、价格、迁移、财政转移支付或其组合实现。每种机制分配负担的方式不同。人口迁移可减少受影响地区的失业，却同时削弱税基、使家庭分离；控制工资可能保住工作，却延长国内需求疲弱的状态。

人们容易把这些后果视为货币联盟本身就是错误的证据，但这忽视了替代方案的成本与风险。即使国内政策审慎，拥有独立货币的小型经济体也可能面临资本流动剧烈波动和高昂融资成本。恰当的比较不是不完美的联盟与毫无摩擦的国家经济，而是不同制度安排如何让人们承担不同形式的不稳定，以及如何分担成本。

这正是共同金融机构的设计为何重要。只有政府耗尽资源后才提供贷款的机制，可能来不及阻止局部紧缩蔓延；但缺乏可信规则的转移支付，又可能削弱出资国的政治支持。解决这种张力不只是选择更大的基金。参与方必须就何为异常冲击、援助附带哪些义务，以及如何区分临时支持与责任永久转移达成共识。

公共讨论常将这些细节视为最好交给专家的技术问题，实际上，它们决定承认谁的损失，又把谁的损失当成竞争不可避免的后果。持久的货币安排要求公民充分理解这些选择，以便提出质疑。否则，被描述为中性约束的规则，可能恰在最需要时失去正当性，迫使政府在压力下临时应对，并使各国选民都相信别国以自身损失为代价获益。可预测性的承诺，最终便依赖于经济设计原本只是预设存在、却未帮助维系的政治关系。`, '反事实汇率调整；税基、财政转移支付；比较对象限定；经济设计预设政治支持的因果倒置。'],
['科学收藏与命名',`When a natural history museum revises the label attached to a specimen, the change can look like an argument about words. In practice, a name connects the object to a network of field notes, publications and assumptions about who is entitled to describe the natural world. A specimen collected during a colonial expedition may be accompanied by meticulous measurements but almost no acknowledgement of the local knowledge that made its identification possible. The completeness of the scientific description should not be mistaken for completeness of the historical account.

Some researchers propose replacing names associated with collectors whose conduct is now considered unacceptable. Others warn that frequent changes would disrupt the stability on which biological classification depends. Both concerns are substantial, but they address different functions of naming. A scientific identifier allows observations made in different places to be compared; a public label also tells visitors whose contribution an institution chooses to commemorate. Treating those functions as identical makes it harder to consider solutions that preserve comparability without perpetuating an unqualified celebration.

A museum might retain a recognised identifier in its catalogue while expanding the information presented beside the specimen. That information could explain how it was obtained, identify the people whose contributions are documented and mark the limits of what is known. Such an approach would not satisfy everyone. An expanded label can still leave the original collector at the centre of the story, especially when the archive preserves his correspondence but not the voices of those who assisted him. Correcting an omission is not always possible simply by adding another sentence.

Nor should uncertainty license invention. Where records do not identify a local guide, assigning a plausible name would create the appearance of recognition at the expense of accuracy. Institutions can instead describe the structural reasons for the absence and invite collaboration with communities whose histories may survive outside official collections. That work takes time and may produce conflicting accounts. Its value should not be measured solely by the number of labels that can be revised before an exhibition opens.

The dispute ultimately concerns how scientific institutions handle the relationship between reliable identification and public responsibility. A collection can remain useful for research while the account of its formation changes. Acknowledging exploitation does not invalidate every observation made with a specimen, just as scientific usefulness does not absolve an institution from examining how it acquired it. Maintaining both propositions requires a form of explanation less convenient than either defending every inherited convention or promising that a new vocabulary can settle an unsettled history. It also requires space for visitors to distinguish evidence of a discovery from the ceremonial choices through which that discovery is remembered, rather than assuming that a single label must perform both tasks without tension.`, `自然历史博物馆修改标本标签时，看上去可能只是在争论用词。实际上，名称将物件与野外笔记、出版物，以及谁有权描述自然世界的观念联系起来。殖民考察中采集的标本，可能附有细致的测量记录，却几乎未承认使鉴定成为可能的地方知识。科学描述完整，不应被误认为历史叙述也完整。

一些研究者建议更换与行为如今被认为不可接受的采集者相关的名字，另一些人担忧频繁更名会破坏生物分类赖以成立的稳定性。两种关切都很重要，但涉及命名的不同功能。科学标识使不同地点的观测能够比较；公开标签还告诉参观者机构选择纪念谁的贡献。将二者视为相同，反而更难考虑既保留可比性、又不延续毫无保留赞颂的方案。

博物馆可以在目录中保留公认的标识，同时扩充标本旁的信息，解释获取方式、列明贡献有记录可查的人，并注明已知范围。这不会令所有人满意。扩充的标签仍可能把最初采集者放在叙事中心，特别是当档案保留了他的通信，却未保留协助者的声音时。弥补遗漏，不一定只加一句话就能做到。

不确定性也不能成为编造的许可。如果记录没有说明当地向导是谁，赋予其一个看似可信的名字，会以牺牲准确性制造承认贡献的表象。机构可以转而说明缺失的结构性原因，并邀请那些历史可能保存在官方收藏之外的社群合作。这需要时间，也可能产生冲突的叙述。不能只按展览开幕前改了多少标签来衡量其价值。

争议最终涉及科学机构如何处理可靠鉴定与公共责任的关系。收藏可以继续服务研究，而关于其形成的叙述可以改变。承认剥削，并不会使利用标本作出的每项观测失效；科学价值也不会免除机构审视获取方式的责任。同时坚持这两点，需要一种更不便捷的解释，既不维护所有继承的惯例，也不承诺新词汇能解决未定的历史。还需要让参观者有空间区分发现的证据与纪念发现的仪式性选择，而不是假定一个标签能毫无冲突地同时履行两项任务。`, 'identifier/commemoration语义分离；双向否定类比；认识论与机构责任交错。'],
['保险与气候迁移',`Insurers withdrawing from exposed coastal districts are often accused of abandoning communities just when protection is most needed. The accusation expresses a real predicament, but it does not explain how losses should be distributed. Insurance pools uncertain losses across policyholders. When repeated flooding becomes increasingly predictable, the question shifts from how to share an occasional accident to who should finance continued occupation of a place whose risks are rising. Keeping premiums low does not make that question disappear.

A public guarantee can prevent an abrupt collapse in coverage. Without one, homeowners may lose access to mortgages, local property values may fall and councils may struggle to maintain services as their tax base shrinks. These effects can reinforce one another long before a neighbourhood becomes physically uninhabitable. Yet a guarantee that does not distinguish existing residents from new development may encourage further construction in precisely the areas where future protection will be most expensive. A measure intended to prevent immediate hardship can thereby enlarge the eventual obligation.

Managed relocation is sometimes offered as a clear alternative. For households, however, a payment based on the market value of a property may be insufficient to purchase a comparable home elsewhere, particularly if prices have already fallen because of the risk. Tenants may receive no payment at all while losing employment, social networks and access to familiar services. A policy framed entirely around property ownership therefore misses much of what relocation costs. The absence of a registered asset does not mean the absence of a substantial loss.

Designing assistance requires decisions about timing as well as eligibility. Waiting for another disaster may make the need politically undeniable, but can also destroy the evidence and resources needed for an orderly move. Acting earlier can look premature to residents who have survived previous warnings. Authorities need to explain why changing probabilities matter even when the date of the next flood cannot be predicted. They should also make clear which protections will be maintained during a transition and which commitments cannot credibly be extended indefinitely.

No arrangement eliminates the conflict between protecting current residents and limiting future exposure. The more defensible policies make that conflict visible rather than disguising it as a purely technical dispute about premiums. They distinguish assistance to people from a promise to preserve every existing use of land, and they provide a way to revise decisions as conditions change. Otherwise, temporary guarantees can harden into expectations that become both more costly to honour and more damaging to withdraw. A transparent transition may still be painful, but it avoids asking households to plan their futures around assurances whose financial and physical limits have never been stated.`, `保险公司退出高风险沿海地区时，常被指责在人们最需要保障时抛弃社区。这种指责表达了真实困境，却未说明损失应如何分配。保险是在投保者之间分摊不确定的损失。当反复洪灾越来越可以预见时，问题就从如何分担偶发事故，转变为谁应为继续居住在风险上升地区出资。维持低保费并不能使这个问题消失。

公共担保可以防止保障突然崩溃。缺乏担保时，房主可能无法获得按揭贷款，房价可能下跌，地方政府也可能因税基萎缩而难以维持服务。在社区尚可居住时，这些影响就可能相互强化。然而，不区分原有居民与新增开发的担保，可能刺激人们恰在未来保护成本最高的地区继续建设。旨在避免眼前困难的措施，因而可能扩大最终责任。

有计划的迁移有时被视为明确的替代方案。但按房产市值支付的补偿，可能不足以让家庭在别处买到相当住房，尤其当风险已经导致房价下跌时。租户可能一无所得，却失去工作、社交网络和熟悉的服务。因此，完全围绕房产所有权制定政策，会遗漏迁移的大量成本。没有登记资产，并不意味着没有重大损失。

援助设计既要决定资格，也要决定时间。等待下一次灾害，可能使需求在政治上无法否认，却也可能毁掉有序搬迁所需的证据与资源。对经历过以往预警而安然无恙的居民来说，提前行动又可能显得过早。政府需要解释，即使无法预测下一次洪水的日期，概率变化为什么仍然重要；同时说清过渡期内会维持哪些保护，哪些承诺无法可信地无限延长。

没有安排能消除保护当前居民与限制未来风险之间的冲突。更有根据的政策会使冲突清晰可见，而非把它伪装成关于保费的纯技术争论。它们区分对人的援助与保留每一种现有土地用途的承诺，并提供随条件变化而修订决定的途径。否则，临时担保可能固化为预期，使兑现日益昂贵、撤回日益有害。透明的过渡仍可能痛苦，但至少不会要求家庭围绕从未说明财务和物理限度的保证来规划未来。`, '可保风险与可预期损失；反身强化链；财产权与实际损失；which限制结构和时间尺度。']
];
