import {EXAM_EVIDENCE} from './examEvidence.js';
import {ADDITIONAL_EXAM_EN} from './additionalExamEn.js';
import {reviewedSeed} from '../content/seedReview.js';
const zh=[
['城市防洪','城市防洪规划往往以历史上最大的降雨量为依据，但气候变化正在削弱这种做法的可靠性。对于一座已经建成的城市，问题不是能否彻底消除积水，而是在有限预算下，优先保护哪些设施，并为超出设计标准的降雨保留应对空间。新建排水管道固然重要，维护现有设施、恢复湿地和减少地表硬化同样不可忽视。尤其需要注意的是，低收入居民往往居住在风险较高的地区，却未必有能力承担改造期间的搬迁费用。如果工程只按照土地价值排序，最需要保护的人反而可能最后受益。因此，规划部门应公开不同方案的成本和受益范围，邀请居民核查风险地图，并把临时安置纳入项目预算。评价一项防洪工程，不仅要看它能排走多少水，还要看当保护能力达到极限时，城市能否及时预警，让居民安全撤离。','Urban flood planning often relies on the highest rainfall recorded in the past, but climate change is making that approach less reliable. For an established city, the question is not whether flooding can be eliminated altogether. It is which facilities should receive priority protection within a limited budget and how to retain the capacity to respond to rainfall exceeding design standards. Building new drainage pipes is important, but maintaining existing facilities, restoring wetlands and reducing impermeable surfaces must not be overlooked. Particular attention is needed because low-income residents often live in higher-risk areas yet may be unable to afford relocation during construction. If projects are ranked solely by land value, those most in need of protection may benefit last. Planning authorities should therefore disclose the costs and coverage of different proposals, invite residents to check risk maps and include temporary accommodation in project budgets. A flood protection project should be assessed not only by how much water it can remove, but also by whether the city can issue timely warnings and enable residents to evacuate safely when its protective capacity reaches its limit.'],
['科研评价','科研评价中的一个难题，是如何识别那些尚未产生直接应用价值、却可能改变未来研究方向的工作。论文数量便于统计，但不能充分反映研究者提出的问题是否重要，也无法说明一个结论能否经受重复检验。对年轻研究者而言，过分强调短期产出还可能使他们避开高风险课题，转而选择更容易发表的研究。改革评价制度并不意味着放弃问责，而是要求评价者说明判断的依据，允许不同学科采用不同的时间尺度。研究机构可以将数据共享、方法验证和团队贡献纳入考察，同时避免把新的指标再次变成机械的排名工具。资助者也需要区分诚实探索中的失败与研究过程中的失职。只有在合理的监督下为不确定性保留空间，公共科研资金才可能既回应当前需求，又支持那些暂时无法预测用途的发现。','One difficulty in evaluating research is identifying work that has not yet produced directly useful applications but may change the direction of future inquiry. Publications are easy to count, but their number does not adequately reveal whether researchers are asking important questions or whether a conclusion can withstand replication. For early-career researchers, an excessive emphasis on short-term output may also encourage them to avoid high-risk questions in favour of work that is easier to publish. Reforming evaluation does not mean abandoning accountability. It requires evaluators to explain the basis for their judgments and allows different disciplines to operate on different timescales. Research institutions can consider data sharing, methodological verification and contributions to teams, while avoiding turning new indicators into another mechanical ranking tool. Funders also need to distinguish failure in honest exploration from negligence in the research process. Only by allowing room for uncertainty under reasonable oversight can public research funding both address current needs and support discoveries whose uses cannot yet be predicted.'],
['文化与旅游','一座历史街区吸引游客之后，保护工作可能面临新的矛盾。修缮建筑可以改善环境，但商业租金随之上涨，原有的小店和居民可能被迫离开。假如街区只剩下统一设计的招牌和出售纪念品的店铺，游客看到的虽然整洁，却未必是当地文化仍在延续的证据。管理者因此需要把居民的居住条件、传统行业的经营空间和公共设施的承载能力纳入保护方案，而不能只统计门票收入。对确有安全隐患的建筑，应明确维修责任并提供必要支持；对没有经营收益却具有公共价值的空间，则需要稳定的维护资金。居民参与决策也不应局限于方案公布后的意见征集，而应从目标确定时就开始。文化保护的关键，不是让街区永远停留在某个历史时刻，而是在变化中保留其生活基础，使保存下来的建筑仍然能够承载真实的社会关系。','Once a historic district attracts visitors, conservation may face new tensions. Restoring buildings can improve the environment, but commercial rents may rise and force existing small shops and residents to leave. If all that remains is uniformly designed signage and souvenir shops, the neat appearance visitors see is not necessarily evidence of a living local culture. Managers therefore need to incorporate residents’ housing conditions, space for traditional businesses and the capacity of public facilities into conservation plans, rather than simply counting ticket revenue. For buildings with genuine safety hazards, responsibility for repairs should be clarified and necessary support provided. Spaces that generate no commercial income but have public value need stable maintenance funding. Nor should resident participation be limited to commenting after a proposal has been announced; it should begin when objectives are being set. The key to cultural conservation is not to keep a district permanently at a particular moment in history. It is to preserve the basis of its everyday life amid change, so that the buildings retained can continue to accommodate real social relationships.'],
['供应链','企业重新安排供应链时，常把供应商数量增加视为降低风险的直接办法。然而，如果几家供应商依赖同一座港口、同一种原料或同一个上游生产商，表面上的多元化并不意味着风险真正分散。采购部门需要了解关键环节之间的联系，而不能仅凭合同上的不同名称作出判断。建立备用产能也有成本，尤其是当这些设备长期闲置时，小企业可能难以承担。因此，韧性建设需要在库存、信息共享和供应商合作之间作出选择，而不是要求每个环节都无限增加储备。与此同时，向供应商提出更严格的交货要求，却不给予合理的付款期限，可能把风险转移给最缺乏承受能力的一方。真正可靠的供应体系，应允许各方及时报告困难，并在中断发生前共同调整计划。评估其成效时，既要考虑恢复速度，也要关注维持这种能力所需的成本由谁承担。','When reorganising supply chains, companies often regard increasing the number of suppliers as a straightforward way to reduce risk. Yet if several suppliers depend on the same port, raw material or upstream producer, apparent diversification does not mean that risks have genuinely been spread. Procurement departments need to understand connections between critical stages rather than judge solely by the different names on contracts. Maintaining spare capacity also has costs, particularly when equipment remains idle for long periods, which small firms may struggle to bear. Building resilience therefore requires choices among inventory, information sharing and supplier cooperation, rather than demanding unlimited reserves at every stage. At the same time, imposing stricter delivery requirements without allowing reasonable payment terms may shift risk to the party least able to withstand it. A truly reliable supply system should enable all parties to report difficulties promptly and adjust plans together before a disruption occurs. Its effectiveness should be assessed in terms not only of recovery speed, but also of who bears the costs of maintaining that capacity.']
];
const en=[
['公共能源投资',`A community energy project can look attractive on a balance sheet while remaining inaccessible to the people it is intended to serve. In one proposed scheme, households would buy shares in a solar installation and receive a portion of the revenue from electricity sales. The projected return was modest but relatively stable. For homeowners with savings, the offer provided a way to support cleaner energy without installing equipment on their own roofs. For tenants struggling with monthly bills, however, an invitation to invest did little to reduce immediate financial pressure.

The organisers initially considered lowering the minimum investment. Consultation revealed that this would address only part of the problem. Some residents were reluctant to commit even a small amount because they could not predict when they might need it back. Others expected to move and did not know whether their membership would remain valid. The obstacle was therefore not simply the price of a share, but the distribution of uncertainty between the project and individual households.

A revised design allocated some revenue to a local fund that helped residents improve insulation. Access to that fund did not depend on share ownership. The scheme also introduced clear rules for transferring shares and published estimates showing how returns would change under different electricity prices. These changes reduced the money available for investors in the short term. They also made it harder to describe the project as a simple financial product with one easily advertised rate of return.

Critics argued that the project was being asked to pursue too many objectives. They had a point: an energy cooperative cannot substitute for a comprehensive housing policy, and promises of broad social benefits can conceal weak commercial assumptions. The organisers responded by separating the accounts of the installation from those of the local fund. Residents could then see which benefits came from selling power and which depended on an explicit decision to redistribute income.

The revised scheme did not remove every barrier to participation. It did, however, change the question used to judge success. Rather than asking only how much renewable electricity had been generated, the community could examine who had gained financial security and who still faced difficulties. That distinction matters whenever public support is used to encourage private investment. An initiative should not be called inclusive merely because everyone is allowed to apply; its conditions must also be examined from the perspective of those least able to absorb a loss. Doing so requires attention to timing as well as totals, since a benefit delivered several years later cannot necessarily meet a household's need today. For the cooperative, acknowledging this limit became part of responsible communication rather than evidence that the entire project had failed.`,
'社区能源项目在财务报表上可能很有吸引力，却仍让其本应服务的人群难以参与。在一项拟议方案中，家庭可以购买太阳能设施的股份，并获得售电收入的一部分。预计收益不高，但相对稳定。对于有储蓄的房主，这提供了一种无须在自家屋顶安装设备就能支持清洁能源的方式。然而，对每月支付账单都感到困难的租户而言，邀请他们投资并不能缓解眼前的经济压力。\n\n组织者最初考虑降低最低投资额。协商发现，这只能解决部分问题。一些居民连小额资金也不愿投入，因为他们无法预知何时需要收回。另一些人可能搬家，不清楚会员资格届时是否仍然有效。因此，障碍不仅在于股价，还在于项目与各个家庭之间如何分担不确定性。\n\n修改后的设计将部分收入拨给一个地方基金，帮助居民改善房屋保温。申请该基金不以持股为条件。方案还明确了股份转让规则，并公布不同电价下收益变化的估算。这些变化减少了投资者短期可得的钱，也使项目更难被描述为一种只有一个易于宣传的收益率的简单金融产品。\n\n批评者认为项目承担了过多目标。这一意见有其道理：能源合作社不能替代全面的住房政策，广泛社会效益的承诺也可能掩盖薄弱的商业假设。组织者将发电设施与地方基金分别记账作为回应。居民由此可以分辨哪些收益来自售电，哪些取决于明确的收入再分配决定。\n\n修改后的方案没有消除所有参与障碍，却改变了衡量成功的问题。社区不再只问产生了多少可再生电力，还可以考察谁的经济安全得到改善，谁仍面临困难。只要公共支持被用于鼓励私人投资，这种区别就很重要。不能仅因人人可以申请便称一项举措具有包容性；还须从最无力承受损失者的角度审视其条件。这不仅要看总额，还要看时间，因为数年后获得的利益未必能满足家庭今天的需要。对合作社而言，承认这一局限成为负责任沟通的一部分，而不是整个项目失败的证据。'],
['人工智能与采购',`Public agencies buying automated decision tools often ask suppliers to demonstrate accuracy. The request appears straightforward, but it can conceal several different questions. A system may correctly predict most cases in a test set while performing poorly for a small group whose circumstances are unusual. It may also predict an outcome that reflects past administrative choices rather than an independent measure of need. Before comparing scores, a purchaser must therefore decide what the tool is meant to assist with and which errors would be most costly.

Consider a system used to prioritise inspections. Historical records show where violations were discovered, not where all violations occurred. Areas inspected more frequently are likely to contribute more examples, even if their underlying rate of non-compliance is no higher. A model trained on those records can reproduce the pattern of inspection and present it as a new discovery about risk. Sending inspectors to the recommended locations then generates further records that seem to confirm the model.

This does not mean that historical data are useless. It means that evaluation should include information about how the data were produced. An agency could reserve some inspections for randomly selected locations, allowing it to compare the model's recommendations with evidence collected independently of them. Such a design has operational costs, and it may initially identify fewer violations than concentrating entirely on familiar locations. Its value lies in testing whether the apparent efficiency can be trusted.

Procurement contracts rarely make these choices visible. They may specify response times and technical availability in detail while leaving the meaning of a successful decision undefined. Agencies also need access to enough documentation to examine changes after deployment. A tool that works under one set of rules may become unreliable when eligibility criteria, reporting practices or the population served changes. Buying a system is therefore the beginning of a monitoring obligation, not the end of an evaluation exercise.

Responsibility cannot simply be transferred to the supplier through a clause stating that the product is accurate. Nor is requiring a human signature on every recommendation sufficient if staff lack time or information to question it. Effective oversight needs a route for affected people to contest decisions and a process for feeding justified objections back into evaluation. These arrangements should be funded alongside the technology. Otherwise, a promise of human control can remain formally intact while having little effect on everyday practice. The relevant question is not whether a machine or a person makes the final move, but whether reasons can be examined, mistakes corrected and authority assigned to someone who can actually change the procedure. Without that capacity, an impressive demonstration offers limited assurance about public value.`,
'公共机构采购自动化决策工具时，常要求供应商证明其准确性。这一要求看似直接，却可能包含几个不同的问题。一个系统可能正确预测测试集中的大多数案例，但对情况特殊的小群体表现不佳。它预测的结果也可能反映过去的行政选择，而非对需求的独立衡量。因此，在比较分数之前，采购方必须决定工具要协助处理什么，以及哪些错误代价最大。\n\n以用于确定检查优先次序的系统为例。历史记录反映的是在哪些地方发现了违规，而不是所有违规发生在哪里。被检查得更频繁的地区可能贡献更多样本，即使其实际违规率并不更高。用这些记录训练的模型可能重现过去的检查模式，却将其呈现为关于风险的新发现。把检查人员派往推荐地点，又会产生似乎印证模型的新记录。\n\n这并不意味着历史数据无用，而是评估应包含数据如何产生的信息。机构可以将部分检查安排在随机选择的地点，从而用独立于模型推荐所收集的证据进行比较。这种设计会产生运营成本，最初发现的违规也可能少于完全集中检查熟悉地点的做法。其价值在于检验表面上的效率是否可信。\n\n采购合同很少让这些选择清晰可见。它们可能详细规定响应时间和技术可用性，却不定义成功决策的含义。机构还需要获取足够的文档，以便检查部署后的变化。当资格标准、报告做法或服务人群发生变化时，在一套规则下有效的工具可能变得不可靠。因此，购买系统是持续监测义务的开始，而不是评估工作的结束。\n\n责任不能通过一条声称产品准确的条款简单转移给供应商。如果工作人员没有时间或信息质疑建议，要求每条建议都由人签字也不够。有效监督需要受影响者能够申诉的渠道，以及将有依据的异议反馈到评估中的程序。这些安排应与技术一同获得资金支持。否则，人工控制的承诺在形式上仍然完好，却对日常实践几乎没有作用。关键不在于最终一步由机器还是人执行，而在于理由能否接受审查、错误能否纠正，以及权力能否交给真正能够改变程序的人。没有这种能力，再出色的演示也不能充分保证公共价值。']
];
const ev=topic=>{const e=EXAM_EVIDENCE[topic];return {...Object.fromEntries(['lexicalComplexity','syntacticComplexity','inferenceDemand','discourseComplexity','domainKnowledge','translationChallenges'].map((key,i)=>[key,e[i]])),informationDensity:e[2],crossSentenceReference:e[3],logicalRelations:e[1],register:'正式分析文体：'+e[0],transformationDemand:e[5],mistranslationRisk:e[4],benchmarkIds:['catti2-2022-11-en-zh-1','catti2-2022-11-zh-en-1'],comparison:'WITHIN BENCHMARK：与劳动力定义及职业教育政策稿相比，同样要求保留制度术语、口径和范围；具体挑战：'+e[5]}};
export const REVIEWED_EXAM_PASSAGES=[...zh.map(([topic,sourceText,referenceAnswer],i)=>({id:'exam_reviewed_zh_en_'+String(i+1).padStart(3,'0'),direction:'zh-en',topic,sourceText,referenceAnswer})),...[...en,...ADDITIONAL_EXAM_EN].map(([topic,sourceText,referenceAnswer],i)=>({id:'exam_reviewed_en_zh_'+String(i+1).padStart(3,'0'),direction:'en-zh',topic,sourceText,referenceAnswer}))].map(x=>reviewedSeed({...x,contentType:'exam-passage',type:'paragraph',trainingLevel:'exam-passage',referenceTranslation:x.referenceAnswer,sourceType:'simulated',estimatedMinutes:x.direction==='zh-en'?30:45,contentVersion:1,hints:['先标出论证转折及限定范围。','逐项核查责任主体、因果和否定。']},{tier:'catti-standard',evidence:ev(x.topic),notes:'独立原创模拟材料，逐段核对论点、限定、责任主体和全部句意。属内部编辑判断，未声称人工考官或官方认证。'}));

