import { useCallback, useEffect, useRef, useState } from 'react';
import { COMPANION_LINES } from './companionLines';
const PRIORITY={large_delete:100,resume_after_pause:90,resume_session:90,typing_continuous_40s:80,typing_continuous_20s:70,long_text:60,fast_typing:50,typing_start:40,pause_short:20};
export const CAPTION_COOLDOWN_MS=12000; export const PROGRESS_CAPTION_COOLDOWN_MS=30000;
export default function useTypingBehavior(){
 const [debug,setDebug]=useState({event:'—',caption:'',priority:0,cooldown:0,duration:0,added:0,deleted:0,pause:0});
 const ref=useRef({started:0,lastInput:0,lastValue:'',events:{},lastCaption:'',cooldownUntil:0,pauseTimer:null,sessionStart:0});
 const choose=useCallback((event)=>{const r=ref.current; const now=Date.now(); const cooldown=event.includes('continuous')||event==='long_text'?PROGRESS_CAPTION_COOLDOWN_MS:CAPTION_COOLDOWN_MS; if(now<r.cooldownUntil && PRIORITY[event]<PRIORITY[r.lastEvent||'typing_start']) return; const pool=COMPANION_LINES[event]||[]; let line=pool.find(x=>x!==r.lastCaption)||pool[0]||''; if(!line)return; r.lastCaption=line;r.lastEvent=event;r.cooldownUntil=now+cooldown;setDebug(d=>({...d,event,caption:line,priority:PRIORITY[event],cooldown,duration:r.sessionStart ? now-r.sessionStart : 0,added:d.added,deleted:d.deleted,pause:d.pause}));},[]);
 const onInput=useCallback((value)=>{const r=ref.current,now=Date.now(),prev=r.lastValue||'';const added=Math.max(0,value.length-prev.length),deleted=Math.max(0,prev.length-value.length);if(!r.sessionStart){r.sessionStart=now;r.events={};} else if(now-r.lastInput>60000){r.sessionStart=now;r.events={};choose('resume_session');} if(!r.started){r.started=now;choose('typing_start');} if(deleted>=8)choose('large_delete'); if(added>=80&&!r.events.long_text){r.events.long_text=1;choose('long_text');} if(now-r.sessionStart>=40000&&!r.events.continuous40){r.events.continuous40=1;choose('typing_continuous_40s');} else if(now-r.sessionStart>=20000&&!r.events.continuous20){r.events.continuous20=1;choose('typing_continuous_20s');} if(added>=3)choose('fast_typing'); r.lastInput=now;r.lastValue=value;setDebug(d=>({...d,added: d.added+added,deleted:d.deleted+deleted,duration:r.sessionStart ? now-r.sessionStart : 0,pause:0}));clearTimeout(r.pauseTimer);r.pauseTimer=setTimeout(()=>setDebug(d=>({...d,pause:Date.now()-r.lastInput})),5000);},[choose]);
 const reset=useCallback(()=>{const r=ref.current;r.started=0;r.lastValue='';r.sessionStart=0;clearTimeout(r.pauseTimer);},[]); useEffect(()=>()=>reset(),[reset]); return {onInput,reset,debug,trigger:choose};
}
