import {reviewedSeed} from '../content/seedReview.js';
import {NEW_OBJECTIVE_ROWS} from './objectiveRows.js';
import {SIMULATION_READINGS,SIMULATION_CLOZES} from './passageRows.js';
const ordered=(options,n)=>{const at=(n*3+1)%4;return [...options.slice(at),...options.slice(0,at)]};
const review=(item,notes)=>reviewedSeed({...item,type:'comprehensive',direction:'en-zh',examLevel:'CATTI-2',paperType:'comprehensive',sectionType:'comprehensive-ability',sourceType:'simulated',contentVersion:1},{tier:'catti-standard',evidence:{lexicalComplexity:`语境词义与正式搭配：${notes}`,syntacticComplexity:`审读题干中的否定、从句和修饰关系：${item.topic}。`,inferenceDemand:`由已给证据限制结论，排除无文本依据的断言：${notes}`,discourseComplexity:`${item.topic}的因果、转折和论证层次控制选项成立条件。`,domainKnowledge:`材料提供必要背景，不依赖额外常识补全；主题为${item.topic}。`,translationChallenges:`保留原文所能支持的判断强度，尤其否定与条件：${notes}`},notes});
export const SIM_OBJECTIVES=NEW_OBJECTIVE_ROWS.map(([kind,prompt,options,answer,explanation],i)=>review({id:`rebuild_sim_${kind}_${i+1}`,contentType:kind,questionType:kind,topic:kind==='grammar'?'句法与逻辑范围':'正式语域与语境辨义',sourceText:prompt,prompt,options:ordered(options,i),answer,explanation,referenceAnswer:answer,estimatedMinutes:3},explanation));
export const SIM_READINGS=SIMULATION_READINGS.map((p,i)=>review({...p,id:`rebuild_sim_reading_${i+2}`,contentType:'reading',questionType:'reading',estimatedMinutes:25,questions:p.questions.map(([prompt,options,answer,questionKind,explanation],q)=>({id:`rebuild_sim_reading_${i+2}_q${q+1}`,prompt,options:ordered(options,q+i),answer,questionKind,explanation}))},p.questions.map(q=>q[4]).join('；')));
export const SIM_CLOZES=SIMULATION_CLOZES.map((p,i)=>review({...p,id:`rebuild_sim_cloze_${i+2}`,contentType:'cloze',questionType:'cloze',estimatedMinutes:20,blanks:p.blanks.map(([options,answer,explanation],q)=>({id:`rebuild_sim_cloze_${i+2}_b${q+1}`,prompt:`空格 ${q+1}`,options:ordered(options,q+i),answer,explanation}))},p.blanks.map(q=>q[2]).join('；')));
export const SIMULATION_CONTENT=[...SIM_OBJECTIVES,...SIM_READINGS,...SIM_CLOZES];
