import {CALIBRATION_ZH} from './calibrationZh.js';
import {CALIBRATION_EN} from './calibrationEn.js';
import {TRANSLATION_BENCHMARK} from './translationBenchmark.js';
import {characters,words} from './contentValidation.js';
// Editorial comparisons are hypotheses for human review, never publication gates.
const rationales={
calibration_paragraph_zh_01:['相较职教篇的统计口径，本篇要求在“未记录”与“有意压制”之间保留证据强度，不能把推断写成事实。','相较丝路篇省略主语的补足，本篇主语在编纂者、商人与史家间切换，并要求译出相反解释的让步关系。','相较碳汇篇定义和数量限定，本篇需要精确区分历史分类与后世概念，灾异、共同体并非可直接套词的对应。'],
calibration_paragraph_zh_02:['相较职教篇不同统计总体，本篇区分排放账簿边界与实体排放，移除任何限定都会改变结论。','相较丝路篇并列行动，本篇的交易、监管、投资者动机形成多级条件，不能把可能性提升为既成因果。','相较碳汇篇吸收与减排机制，本篇区分局部减排、总量变化、控制权和责任，不靠术语堆砌制造困难。'],
calibration_exam_zh_01:['相较职教篇插入案例，本篇在原作者、译者与当代读者之间切换时点；“陈旧”与写作当时“古雅”不可混淆。','相较丝路篇政策隐喻，本篇“搬运、入口、标本”构成对照论证，直译任一词不足以保全逻辑。','相较碳汇篇定义显化，本篇“成立、含混、版本依据”须据翻译语境处理，同时保留并非全盘否定解释的让步。'],
calibration_exam_zh_02:['相较职教篇公平和统计指标，本篇要区别名义准入、实际实验能力和使用率，不能用access重复覆盖三层。','相较丝路篇主体转换，本篇资助申请、考核、管理者选择和损失承担者的主语必须清楚转换。','相较碳汇篇机制说明，本篇从考核激励推到项目筛选，再反驳平均机时方案，连续运行时间不等于总量。'],
calibration_paragraph_en_01:['相较劳动力篇定义限定，本篇it回指整个命题，行政精确性与历史正当性是不同判断。','相较疫情运输篇让步张力，本篇两次否定均非全盘否定地图；not because限定必须保留。','相较柬埔寨篇新闻与制度联动，本篇将调查分类、赔偿依据与权利效力连成隐含因果链，不可概括成地图不准确。'],
calibration_paragraph_en_02:['相较劳动力篇分类和统计口径，本篇reviewer/readers视角重复有讽刺功能，terms不是一般词语而是比较框架。','相较疫情运输篇行动并列，本篇否定范围和让步反转更集中，must always be wrong不能误译成总是正确。','相较柬埔寨篇修辞转换，本篇local colour与certificate隐喻要连贯，不能丢失选择性证据与文化标签的关系。'],
calibration_exam_en_01:['相较劳动力篇定义，本篇insured event、experience和policy分类界限贯穿各段，不能用风险一词抹平。','相较疫情运输篇危机和政策关系，本篇以多重if/yet/while区分定价必要性、协商正当性与风险公平。','相较柬埔寨篇供需和个体故事，本篇由企业账目转向家庭预算，再区分既有损失与未来激励，末段no more...than保留双重否定。'],
calibration_exam_en_02:['相较劳动力篇统计分类，本篇authorship、credit、attribution分别承担署名、归功和归属功能。','相较疫情运输篇跨句关系，本篇without which、whose和necessary though嵌套修饰多层，不能把不可识别个人推导成无人贡献。','相较柬埔寨篇新闻人物，本篇将实物处理链转成知识署名链，再到利益分配；简洁标签与未解争议有持续让步关系。']};
const supplements={
calibration_v2_zh_exam_01:['此外，社区反馈应定期进入预算调整，而不是只在项目结束时被记录。','In addition, community feedback should enter budget revisions regularly rather than being recorded only after a project ends.'],
calibration_v2_en_para_01:['When a platform controls when an offer appears or penalises a refusal, the arrangement may resemble employment even if the contract says otherwise. Portability also requires that contributions be visible to the worker, not merely exchanged between companies. It should also be clear who keeps the account when a platform closes, and whether a worker can challenge an inaccurate record. Otherwise portability exists on paper but disappears at the moment it is most needed in practice.','当平台控制工作何时出现或因拒绝而惩罚劳动者时，即使合同另有表述，这种安排也可能接近雇佣关系。可转移性还要求缴费对劳动者透明，而不能只在企业之间交换。'],
calibration_v2_en_para_02:['The mission should also define who may halt a procedure when new evidence changes the risk assessment. That authority cannot be left to publicity schedules or to the institution that would bear the cost of delay. A clear separation between scientific judgement and promotional pressure is therefore part of containment itself. It matters equally after arrival: a result that is inconvenient for a launch narrative must remain reportable, and a negative finding should count as knowledge rather than as a failed investment. Long-term custody should be funded before the first sample is opened. It should remain possible to inspect the chain of decisions years later, when the original team and political promises may have changed.','任务还应明确，在新证据改变风险评估时，谁有权暂停程序。这一权力不能交给宣传日程，也不能交给承担延期成本的机构。因而，把科学判断同宣传压力分开，本身就是封存措施的一部分。'],
calibration_v2_en_exam_01:['Reserve managers must also consider the quality of what is released. Grain that has been stored badly may satisfy a headline quantity target while failing to provide safe nutrition. Procurement rules can therefore be as important as release rules. They should require independent inspection, publish the age and condition of stocks and make clear who is responsible when a shipment is rejected. Such details may seem administrative, yet they determine whether an emergency policy reaches a kitchen rather than stopping at a warehouse. The same principle applies to imports: relying on foreign supplies during a local shortage may ease pressure, but it exposes the reserve to transport delays, export restrictions and currency shocks. A policy that counts only domestic tonnage may therefore appear resilient while depending on risks outside its control. It should also disclose how long stocks can be kept safely and how quality is checked when warehouses are privately operated. These details affect whether a reserve can respond to a crisis rather than merely exist in an inventory. They also affect public trust: households need to know whether a release is temporary relief or a sign that the system has been exhausted. Publishing the reasoning behind each decision allows later officials to learn from a mistake without pretending that uncertainty was absent.','储备管理者还必须考虑投放粮食的质量。储存不当的粮食或许能满足数量指标，却不能提供安全营养。因此，采购规则可能与投放规则同样重要。规则应要求独立检验，公布储备的储存年限和状况，并明确货物被拒收时由谁负责。这些细节看似行政安排，却决定应急政策能否进入家庭厨房，而不是停留在仓库。进口也遵循同一原则：地方短缺时依赖外部供应或可缓解压力，却会使储备暴露于运输延误、出口限制和汇率冲击。一项只计算国内吨位的政策，可能看似有韧性，实际却依赖自身无法控制的风险。'],
calibration_v2_en_exam_02:['Monitoring must include the aquifer itself, not only the monument. A change that appears harmless at the site may alter the water available to households several kilometres away. Nor can consultation be reduced to a meeting after the technical design is complete. Residents need enough information to question the model before the choice becomes irreversible. If the evidence remains contested, a temporary trial with a published stopping rule may be more responsible than a permanent commitment made in the name of certainty. The trial should report failures as carefully as successes, since a dry well or a damaged wall may reveal a connection that the original model ignored. Local knowledge cannot replace measurement, but it can indicate where measurement has been too narrow. A decision that combines both is easier to revise without treating revision as an admission that the first attempt was irrational. The review should be public enough to show why thresholds changed, while protecting households from being turned into evidence without consent. The authority to pause pumping should be independent of the body responsible for construction, and the review should explain who pays when a protective measure is withdrawn. It should record whether residents accepted the change freely or only because no practical alternative was offered in the particular circumstances at hand.','监测对象必须包括含水层本身，而不只是遗址。遗址处看似无害的变化，可能改变数公里外家庭可获得的水量。协商也不能简化为技术设计完成后的说明会。居民需要足够信息，在选择尚未不可逆之前质疑模型。如果证据仍有争议，制定公开停止规则的临时试验，可能比以确定性名义作出的永久承诺更负责任。']
};
const enV3={
calibration_v2_en_para_01:[CALIBRATION_EN.find(x=>x.id==='calibration_v2_en_para_01').sourceText+' '+`Where a platform decides which requests are visible, how quickly a courier must accept them, and whether declining an offer will reduce future access, the contractual freedom that appears on paper may coexist with a practical dependence that neither party can describe by looking at a single delivery record.`,CALIBRATION_EN.find(x=>x.id==='calibration_v2_en_para_01').referenceAnswer+' '+`如果平台决定哪些订单可见、快递员必须多快接单，以及拒绝订单是否会减少未来获得工作的机会，那么纸面上存在的合同自由，可能同实际依赖并存；而这种依赖并不能从任何一条配送记录中单独看出。`],
calibration_v2_en_para_02:[CALIBRATION_EN.find(x=>x.id==='calibration_v2_en_para_02').sourceText+' '+`Because the danger cannot be established by inspection before the material is opened, the people who authorise the mission must decide in advance not only what evidence would justify proceeding, but also who may stop the procedure when a result that is scientifically valuable nevertheless makes the original containment assumptions untenable.`,CALIBRATION_EN.find(x=>x.id==='calibration_v2_en_para_02').referenceAnswer+' '+`由于在打开样本前不可能通过检查确定危险，批准任务的人必须预先决定：什么证据足以支持继续，以及当具有科学价值的结果却使原有封存假设无法成立时，谁有权停止程序。`],
calibration_v2_en_exam_01:[CALIBRATION_EN.find(x=>x.id==='calibration_v2_en_exam_01').sourceText+' '+`Although a release that prevents a temporary shortage from becoming a national crisis may be politically attractive, officials who know that the same release can depress next season’s planting decisions must weigh a benefit that is immediate and visible against a cost that, because it is distributed across thousands of farms and appears only months later, is easily omitted from public accounts.`+' '+`The difficulty is compounded when stocks are held by contractors whose commercial incentives, unless they are checked by independent inspection and transparent rotation rules, can make a reserve look full while leaving the usable portion uncertain.`,CALIBRATION_EN.find(x=>x.id==='calibration_v2_en_exam_01').referenceAnswer+' '+`尽管一次投放若能防止暂时短缺演变为全国性危机，政治上或许很有吸引力，但官员明知同一投放也可能压低下一季的种植意愿，就必须在眼前且可见的收益与一种容易从公开账目中遗漏的成本之间权衡；这种成本分散在数千个农场，往往要到数月后才显现。`+' '+`如果储备由承包商保管，且其商业动机没有受到独立检验和透明轮换规则的约束，困难会进一步加剧：储备看似充足，可实际可用部分却难以确定。`],
calibration_v2_en_exam_02:[CALIBRATION_EN.find(x=>x.id==='calibration_v2_en_exam_02').sourceText+' '+`What makes the engineering choice especially difficult is that a measure designed to protect foundations may alter the hydrological conditions on which the surrounding settlements depend, so that a decision whose success is reported at the monument can become, when the monitoring boundary is drawn more widely, the source of a failure borne by households that were never represented in the original design.`+' '+`Before any permanent works begin, the parties should therefore agree on a threshold at which pumping will be reduced, even if doing so means admitting that a model once treated as sufficient no longer explains the evidence.`,CALIBRATION_EN.find(x=>x.id==='calibration_v2_en_exam_02').referenceAnswer+' '+`工程选择之所以尤其困难，是因为旨在保护地基的措施可能改变周围居民点赖以生存的水文条件；如果把监测范围扩大，遗址处被报告为成功的决定，可能反而成为从未参与原始设计的家庭承担的失败根源。`+' '+`因此，在任何永久工程开始前，各方应先约定何种阈值会触发减小抽水，即使这意味着承认曾被视为足够的模型已不能解释证据。`]
};
const enTail={
calibration_v2_en_para_01:['The arrangement is therefore best judged over time, by examining who can refuse work without losing access and who bears the cost when demand collapses. This test matters when the platform changes its ranking system without notice.','因此，最好应当通过长期观察来评估这种安排：谁可以拒绝工作而不失去机会，需求下降时又由谁承担成本。'],
calibration_v2_en_para_02:['A rule that is strict in its wording but impossible to audit in practice may provide reassurance without providing protection. The laboratory must also decide who is accountable when a safeguard delays publication or makes a result less convenient.','一项措辞严格却无法在实践中审计的规则，可能只能制造安心感，不能提供真正保护。'],
calibration_v2_en_exam_01:['The reserve is consequently not a warehouse alone but a sequence of decisions whose consequences become visible at different times and to different groups. The policy must say how evidence is collected before a release, how conflicting forecasts are reconciled, and whether the people who bear the nutritional cost have any role in revising the trigger. Without that information, a formal rule can conceal discretion rather than constrain it. This is why auditability is not a decorative addition to emergency planning: it determines whether officials can be held responsible when a choice produces an effect that was foreseeable only in retrospect. The same record should remain available for later public review.','因此，储备并不只是仓库，而是一连串决策；这些决策的后果会在不同时间、对不同群体显现。'],
calibration_v2_en_exam_02:['The point of the arrangement is not to eliminate uncertainty, but to make its distribution visible before an intervention turns one group’s protection into another group’s unrecorded loss. A plan that identifies only the monument may therefore satisfy a conservation target while obscuring a water crisis outside its boundary. The reviewers should ask not merely whether the structure is safe, but whether the method of making it safe has shifted an avoidable burden onto people who were absent from the original decision. That question, which cannot be answered by a sensor alone, is part of the engineering brief, even when the answer cannot be reduced to one defensible numerical threshold for every individual season.','这种安排的目的不是消除不确定性，而是在干预把一方的保护变成另一方未被记录的损失之前，让不确定性的分配显现出来。']};
const syntaxMetrics=source=>{const sentences=String(source).split(/(?<=[.!?。！？])\s+/).filter(Boolean);const lower=String(source).toLowerCase();const subordinate=(lower.match(/\b(although|because|while|when|which|that|if|unless|where|whose|rather than|even if|so that|before|after|despite)\b/g)||[]).length;const nominal=(lower.match(/\b[a-z]+(?:tion|ment|ity|ness|ance|ence|ship|hood|ism)\b/g)||[]).length;return {sentenceCount:sentences.length,averageSentenceLength:Number((words(source)/Math.max(1,sentences.length)).toFixed(1)),longestSentence:Math.max(...sentences.map(x=>words(x))),subordinateClauseMarkers:subordinate,nominalizationMarkers:nominal,modifierSpanMarkers:(lower.match(/\b(of|whose|which|that|with|without|under|between)\b/g)||[]).length};};
export const CALIBRATION_BATCH=[...CALIBRATION_ZH,...CALIBRATION_EN].map(raw=>{const sup=supplements[raw.id];const v3=enV3[raw.id];const s=v3?{...raw,sourceText:v3[0],referenceAnswer:v3[1]}:sup?{...raw,sourceText:raw.sourceText+' '+sup[0],referenceAnswer:raw.referenceAnswer+' '+sup[1]}:raw;if(v3){s.sourceText+=' '+enTail[s.id][0];s.referenceAnswer+=' '+enTail[s.id][1]}const length=s.direction==='zh-en'?characters(s.sourceText):words(s.sourceText),range=s.kind==='paragraph'?[250,400]:s.direction==='zh-en'?[280,350]:[400,500];return {...s,length,range,lengthGate:length>=range[0]&&length<=range[1]?'PASS':'FAIL',humanDifficultyAcceptance:'pending',published:false,comparison:'MATCH',comparisonMeaning:'编辑比较意见，等待人工盲评；不是自动难度认证',syntaxMetrics:syntaxMetrics(s.sourceText),benchmarks:TRANSLATION_BENCHMARK.filter(b=>b.direction===s.direction).map((b,i)=>({id:b.id,comparison:'MATCH',reason:(rationales[s.id]||['独立主题与结构；需保留限定关系。','跨句逻辑和术语边界构成主要难点。','结论依赖条件与证据强度，不能概括。'])[i%3]}))}});
