import {reviewedSeed} from '../content/seedReview.js';
const evidence=(lex,syntax,inference,discourse,domain,translation)=>({lexicalComplexity:lex,syntacticComplexity:syntax,inferenceDemand:inference,discourseComplexity:discourse,domainKnowledge:domain,translationChallenges:translation});
const rows=[
['vocabulary','监管','The exemption applies only to firms whose annual turnover is below the threshold; larger firms cannot ___ it.', ['invoke','impose','waive','revoke'],'invoke','invoke 指援引既有豁免。impose 是施加规则，waive 是有权者免除义务，revoke 是撤销授权；企业规模条件决定它不能援引豁免。'],
['vocabulary','统计','The apparent rise in unemployment was partly an ___ of the survey redesign: the new questionnaire counted people previously excluded.', ['artifact','impetus','antecedent','inducement'],'artifact','artifact 在研究语境中指测量方法造成的表象；题干明确新增统计对象，并非激励因素 impetus/inducement，也不是时间上在先的 antecedent。'],
['vocabulary','财政','The audit could not ___ the discrepancy with ordinary seasonal fluctuations, since it persisted in every quarter.', ['attribute','account for','ascribe','result in'],'account for','account for the discrepancy with... 表示用某因素解释差异。attribute/ascribe 需要把原因接在 to 后；result in 表示导致，不是解释。每季持续出现排除了季节性解释。'],
['vocabulary','科研','The team described its findings as ___, pending replication by an independent laboratory.', ['provisional','derivative','retrospective','incidental'],'provisional','pending replication 表明结论尚待复现，因此是暂定的 provisional。derivative 指衍生或缺乏原创性，retrospective 指回顾性，incidental 指附带，均不表达证据尚未确认。'],
['vocabulary','劳动','Although the contractor remained legally liable, the agreement ___ day-to-day supervision to the local operator.', ['delegated','relinquished','divested','absolved'],'delegated','delegate responsibility to someone 表示授权执行但未必转移最终责任，与 remained liable 对应。relinquish 不用这一 to 结构；divest 通常为 divest someone of；absolve 是免除某人责任。'],
['vocabulary','档案','The historian treated the later memoir as ___ evidence, useful for checking but not replacing the contemporaneous records.', ['corroborative','dispositive','prescriptive','prospective'],'corroborative','回忆录用于交叉印证而非取代同期记录，因此为 corroborative。dispositive 意味足以定论，与限制相反；prescriptive 是规范性的，prospective 是前瞻性的。'],
['vocabulary','公共健康','The association disappeared once income was controlled for, suggesting that income had been a ___ variable.', ['confounding','dependent','randomized','residual'],'confounding','控制收入后关联消失，说明收入混杂了原来的关联。dependent 是被解释结果，randomized 表示被随机分配，residual 通常指模型未解释的剩余部分；题干不给出因果证明。'],
['vocabulary','基础设施','The bridge was safe for light vehicles, but this did not ___ carrying unrestricted freight traffic.', ['warrant','necessitate','preclude','forestall'],'warrant','安全结论范围只及轻型车辆，不能据此认定无限制货运合理，故 warrant。necessitate 是使必需，preclude/forestall 是排除或预防，与此处证据能支持什么的逻辑不同。'],
['vocabulary','商业','The firm remained solvent but faced a liquidity ___ because customers paid months after suppliers had to be paid.', ['constraint','surplus','windfall','premium'],'constraint','收付款时间错配限制流动资金而非造成资产资不抵债。constraint 是约束；surplus、windfall 都指增加或盈余，premium 是溢价。'],
['vocabulary','国际交流','The joint statement stopped short of endorsing the proposal, merely ___ that it deserved further discussion.', ['acknowledging','ratifying','mandating','enacting'],'acknowledging','stopped short of endorsing 限定为承认值得讨论。ratify 正式批准、mandate 授权强制、enact 立法实施都超过该语气范围。'],
['grammar','政策评估','Had the control group not been retained, the apparent improvement ___ attributed to the intervention alone.', ['might have been','may be','will have been','had been'],'might have been','Had...not been 是 if 省略后的过去反事实条件，主句需情态动词 + have been + 过去分词。may be 指现在，will have been 不表达该反事实，had been 缺少主句情态结构。'],
['grammar','研究方法','Having been excluded from the original sample, ___.', ['the rural households were surveyed separately','the researchers surveyed the rural households separately','a separate survey covered the rural households','the sample was subsequently expanded'],'the rural households were surveyed separately','分词短语逻辑主语须为曾被排除者 rural households。研究者、survey、sample 都不是题干中被排除的家庭，形成悬垂或错误主语。'],
['grammar','公共预算','Not until the revised figures had been independently checked ___ the committee authorize payment.', ['did','had','was','would have'],'did','Not until 置于句首使主句部分倒装，authorize 是原形，须 did。had 后需 authorized，was 不搭配主动 authorize；would have 后也需过去分词。'],
['grammar','教育','The panel recommended that no student ___ solely on the basis of a single automated score.', ['be excluded','is excluded','was excluded','has excluded'],'be excluded','recommend that 的正式建议从句用虚拟原形 be；学生是被排除者，需被动。其余选项为陈述时态或主动，不符合句法及建议语域。'],
['grammar','环境治理','The permits, each of ___ specifies a maximum discharge, must be renewed annually.', ['which','them','whose','that'],'which','逗号后的非限制性关系从句需 each of which。them 会形成无连接的第二个限定句；whose 需名词作被修饰对象；that 不用于 of 后非限制性关系结构。'],
['grammar','城市交通','So uneven ___ the distribution of services that an average waiting time was misleading.', ['was','did','has','were'],'was','So + 形容词置首引发倒装；主语 distribution 为单数，系动词用 was。did/has 后缺主要动词，were 与单数不一致。'],
['grammar','科技伦理','The question is not whether the system can identify a pattern, but ___ that pattern is relevant to the decision.', ['whether','that','which','what'],'whether','not whether...but whether... 对比两个待判断问题。that 改为已知事实，which/what 在后面完整主谓结构中缺少相应句法位置。'],
['grammar','文化遗产','It was the conflicting accounts, rather than the missing dates, ___ prompted the historian to reopen the inquiry.', ['that','what','whom','whose'],'that','It was ... that 构成强调句，强调 conflicting accounts；rather than 插入对比不改变框架。what 不能接在被强调成分后，whom 不能作 prompted 主语，whose 需名词。'],
['grammar','能源','The project would proceed only if the loan were approved, in which case construction ___ the following spring.', ['would begin','begins','has begun','had begun'],'would begin','前句虚拟条件及后续 in which case 保持条件性未来关系，故 would begin。其他选项分别表示一般现在、已完成及过去之前完成，都不对应尚未满足的条件。'],
['grammar','经济','The consultants objected to ___ required to disclose commercially sensitive estimates.', ['being','be','have been','having'],'being','object to 中 to 是介词，后接动名词；被要求披露需 being required。be 为原形；have been 不能直接接介词；having required 变主动且缺宾语。']
];
export const REVIEWED_OBJECTIVES=rows.map(([kind,topic,prompt,options,answer,explanation],i)=>reviewedSeed({id:'roundb_'+kind+'_'+String(i+1).padStart(3,'0'),contentType:kind,type:'comprehensive',questionType:kind,direction:'en-zh',topic,prompt,sourceText:prompt,options,answer,referenceAnswer:answer,explanation,estimatedMinutes:2,examLevel:'CATTI-2',paperType:'comprehensive',sectionType:'comprehensive-ability',skillTags:[kind,'context'],contentVersion:1},{tier:i===8||i===13||i===19?'foundation':'catti-standard',evidence:evidence(prompt,explanation,'必须结合限定条件排除语法或语义上看似可能的干扰项。','题干的因果、转折或范围限制决定唯一最佳选择。','语境主题：'+topic+'；不要求猜测题干之外的事实。','词义或句法选择需要保留原文限定，而非孤立词义匹配。'),notes:explanation}));
export const REVIEWED_READING=reviewedSeed({
id:'roundb_reading_001',examLevel:'CATTI-2',paperType:'comprehensive',sectionType:'comprehensive-ability',contentType:'reading',type:'comprehensive',questionType:'reading',direction:'en-zh',topic:'档案数字化与代表性',
sourceText:`When a municipal archive digitised its most frequently requested files, online visits rose sharply. Officials initially interpreted the increase as evidence that access had become more inclusive. Yet a subsequent survey found that most new visitors were university researchers and property consultants. Residents seeking records of informal employment or temporary accommodation still struggled to find material relevant to their lives. Their difficulty was not primarily a lack of internet access: many of the events they wanted to investigate had never generated documents that the archive collected.

The digitisation programme had used past requests to decide which files should be scanned first. This seemed an efficient way to meet demonstrated demand. However, the requests reflected the interests of people who already knew the catalogue and could afford to visit during working hours. Making the same material available online removed one barrier while preserving another. The programme amplified an existing pattern of visibility rather than simply reproducing a neutral record of the city.

Archivists proposed collecting oral accounts and inviting neighbourhood organisations to identify gaps. Some historians welcomed the proposal but warned against treating memory as an unproblematic substitute for documentation. An account recorded decades after an event may compress chronology or reflect later interpretations. Written records have limitations too: an official form may accurately describe an administrative decision while revealing little about its consequences for the people affected.

The archive therefore began linking interviews to surviving documents and explaining where accounts differed. It also retained information about who had selected each collection and why. These measures did not produce a single authoritative narrative, nor did they guarantee equal representation. They made the process of selection easier to examine. The director argued that success should be assessed partly by whether users could recognise the limits of the collection, not merely by how many files they downloaded. That change in emphasis made the programme harder to summarise in a headline statistic, but more useful as an invitation to investigate the city's past.`,
questions:[
['main-idea','Which claim best captures the argument?',['Digital access alone cannot correct biases in what an archive contains.','Oral testimony should replace official documentation.','University researchers are responsible for missing records.','Download totals have no administrative value.'],'Digital access alone cannot correct biases in what an archive contains.','访问量增加但部分居民经历从未被收录，说明可访问性与收录偏差是不同问题；全文并未主张替代文献或否定所有计数。'],
['inference','Why might prioritising frequently requested files reinforce exclusion?',['Past demand came disproportionately from people already able to use the archive.','The most requested files were too fragile to scan.','Consultants were prohibited from using paper records.','Neighbourhood groups demanded fewer online services.'],'Past demand came disproportionately from people already able to use the archive.','第二段请求样本受既有目录知识和到馆时间影响，需求不是全体居民需求的无偏测量；其余原因无原文依据。'],
['reference','In “preserving another”, what is the second barrier?',['The limited representation of experiences in the selected records.','The need to use a computer inside the archive.','A ban on researchers visiting during working hours.','The chronological ordering of every interview.'],'The limited representation of experiences in the selected records.','网上开放消除了到馆障碍，却保留了选择和收录范围的障碍；需结合第一段未产生记录及第二段选择机制理解 another。'],
['attitude','How does the author present oral accounts?',['As useful evidence that requires critical comparison with other sources.','As inherently more reliable than official forms.','As unsuitable for any historical investigation.','As a cheap way to avoid explaining disagreements.'],'As useful evidence that requires critical comparison with other sources.','第三段同时指出记忆与文献局限，第四段将访谈与文献互证并公开分歧，态度为有条件认可而非全盘赞同或否定。'],
['argument','What role does the final paragraph play?',['It offers a response to selection bias while acknowledging the limits of that response.','It proves that representation has become equal.','It retracts the need for digitisation altogether.','It identifies a technical cause of missing downloads.'],'It offers a response to selection bias while acknowledging the limits of that response.','最后段提出链接、记录选择过程及新的评估标准，同时明确未保证平等代表，属于回应问题并限定成效。']
].map(([questionKind,prompt,options,answer,explanation],i)=>({id:'roundb_reading_001_q'+(i+1),questionKind,prompt,options,answer,explanation})),
estimatedMinutes:12,skillTags:['inference','argument','reference','attitude'],contentVersion:1
},{tier:'catti-standard',evidence:evidence('amplified, chronology, authoritative narrative 区分记录与解释层次。','让步、限制性从句和同位解释服务于多段论证。','推断过去需求为何不是未服务人群需求的代表。','先提出成效表象，再分析选择偏差，最后给出有限回应。','公共档案的收集、访问与证据互证之间有概念差别。','保留 merely、partly 和 nor 等限制词，不把有限改进译成问题已解决。'),notes:'五题分别审查主旨、推断、指代、态度及论证；每个答案均在解析中对应原文理由。'});
const clozeText=`An evaluation of a river restoration programme began with an uncomfortable finding. Fish numbers had risen upstream, but the team could not (1) ___ the increase to restoration alone. Rainfall had also been unusually high. To distinguish the two influences, researchers compared restored sections with similar sections that had received no intervention. These comparison sites were not perfect: their water temperature differed slightly. (2) ___, they provided a more credible basis for inference than a simple before-and-after count.

The initial report described the results as (3) ___ rather than conclusive. Local officials worried that this qualification would be read as failure, (4) ___ the researchers saw it as a reason to continue measurement. They agreed to publish the methods alongside the findings, so that readers could (5) ___ the strength of the evidence for themselves. Volunteers collected further observations, but only after (6) ___ training in how to record them consistently.

Over time, the partnership changed the way success was discussed. Restoring a river was no longer treated as a project that ended when construction was (7) ___. It became a process in which maintenance and monitoring were (8) ___. This did not mean postponing every decision until uncertainty vanished. It meant making decisions (9) ___ to revision when stronger evidence emerged. The distinction mattered because confidence in the programme depended less on promises of certainty than on a visible willingness to (10) ___ mistakes.`;
const blanks=[
[['attribute','distribute','contribute','allocate'],'attribute','attribute A to B 表示将变化归因于某因素；其他动词不表示归因，后文降雨是混杂因素。'],
[['Nevertheless','Consequently','Similarly','Otherwise'],'Nevertheless','温度不同是局限，但比较组仍优于简单前后对比，需让步转折而非结果、相似或否则。'],
[['provisional','definitive','incidental','redundant'],'provisional','rather than conclusive 及继续监测限定为暂定结论；其余分别为定论、附带和多余。'],
[['whereas','because','unless','once'],'whereas','官员视为失败与研究者视为继续测量理由形成对比；不是因果、条件或时间先后。'],
[['assess','assure','assign','assert'],'assess','读者凭公开方法评估证据强度，assess 的宾语搭配适切；不是保证、分派或宣称强度。'],
[['receiving','received','receive','to receive'],'receiving','after 为介词，接 receiving training；其余不是介词可直接支配的名词性形式。'],
[['completed','exhausted','fulfilled','concluded'],'completed','construction was completed 是工程完工；fulfil 通常是义务，exhaust 是耗尽，conclude 是讨论/事件结束而非完成施工。'],
[['inseparable','interchangeable','dispensable','incidental'],'inseparable','前文要求维护与监测持续并行，故不可分；不是可互换、可有可无或附带。'],
[['subject','liable','prone','bound'],'subject','subject to revision 表示可被修订；liable/prone 带不利倾向，bound to 后应接动词原形，均不合此正式政策搭配。'],
[['rectify','ratify','certify','justify'],'rectify','愿意纠正错误才能建立信任；ratify 批准、certify 认证、justify 辩护均不表达纠正。']
];
export const REVIEWED_CLOZE=reviewedSeed({id:'roundb_cloze_001',examLevel:'CATTI-2',paperType:'comprehensive',sectionType:'comprehensive-ability',contentType:'cloze',type:'comprehensive',questionType:'cloze',direction:'en-zh',topic:'河流修复的证据评估',sourceText:clozeText,blanks:blanks.map(([options,answer,explanation],i)=>({id:'roundb_cloze_001_b'+(i+1),prompt:'空格 '+(i+1),options,answer,explanation})),estimatedMinutes:10,skillTags:['cohesion','collocation','causal inference'],contentVersion:1},{tier:'catti-standard',evidence:evidence('attribute、provisional、rectify 等词须在研究语域中选择。','介词后非谓语与被动施工表达均需要句法定位。','降雨混杂使前后比较不足，须理解为何比较组仍有价值。','让步、官员与研究者对比及结尾纠错呼应构成篇章链。','河流生态评价中的比较设计及不确定性解释。','subject to revision 不能处理成必将修订，准确保留条件性。'),notes:'十个空均嵌入连贯正文；完整填回逐项审查语法、搭配和因果，解析说明干扰项。'});

