import assert from 'node:assert/strict';
import {contentAudit,getContentRegistry} from '../src/features/content/contentAudit.js';
import {SENTENCE_EXERCISES} from '../src/features/exercises/sentenceDataset.js';
import {EXAM_PASSAGES} from '../src/features/translation/examPassageDataset.js';
import {FULL_PRACTICE_SETS} from '../src/features/translation/fullPracticeSets.js';
import {READING_PASSAGES,CLOZE_PASSAGES,VOCABULARY_EXERCISES} from '../src/features/comprehensive/comprehensiveDataset.js';
import {toDifficultyTier,toContentStatus,validateDifficultyEvidence} from '../src/features/content/contentDifficulty.js';
import {duplicateWarnings,textSimilarity} from '../src/features/content/contentRegistry.js';
import {checkContent,validateGeneratedContent,markValidated,recordReview,publishContent,fingerprint,reviewValid,checkFullPractice} from '../src/features/content/contentValidation.js';
import {selectPublished,poolNeedsRefill} from '../src/features/content/publishedPool.js';
import {generateContent,validateGenerationRequest} from '../src/features/content/aiContentSpec.js';
const registry=getContentRegistry();assert.equal(new Set(registry.items.map(x=>x.id)).size,registry.items.length);
const audit=contentAudit();assert.equal(audit.valid,true,JSON.stringify(audit.publishedFailures));
assert.ok(audit.rejected.length>0);assert.equal(audit.duplicateDetection.published.length,0);assert.ok(audit.duplicateDetection.allCandidates.length>0);
assert.equal(toDifficultyTier('hard'),null);assert.equal(toDifficultyTier('catti2'),null);
assert.equal(toContentStatus({reviewStatus:'approved'}),'draft');
assert.equal(validateDifficultyEvidence({}),false);
for(const state of ['draft','validated','reviewed','rejected'])assert.equal(selectPublished([{...SENTENCE_EXERCISES[0],contentStatus:state}]).length,0);
assert.equal(selectPublished([{...SENTENCE_EXERCISES[0],referenceAnswer:'wrong'}]).length,0);
assert.ok(poolNeedsRefill(getContentRegistry().items).length>0);
const example=SENTENCE_EXERCISES[0];
assert.ok(reviewValid(example));
assert.equal(checkContent(null).valid,false);assert.equal(checkContent({...example,sourceText:23}).valid,false);assert.equal(checkContent({...READING_PASSAGES[0],questions:5}).valid,false);assert.equal(checkContent({...VOCABULARY_EXERCISES[0],options:[1,2,3,4]}).valid,false);assert.equal(reviewValid({...example,sourceText:example.sourceText+'!'}),false);

assert.equal(checkContent({...example,sourceText:example.referenceAnswer}).valid,false);
assert.equal(checkContent({...example,referenceAnswer:example.sourceText}).valid,false);
assert.equal(checkContent({...example,referenceAnswer:'This paragraph discusses public policy.'}).valid,false);
assert.equal(checkContent({...example,sourceText:example.sourceText+' 2027'}).valid,false);
assert.equal(checkContent({...example,difficultyTier:'catti-standard',difficultyEvidence:null}).valid,false);
const a={id:'a',contentType:'paragraph',sourceText:'A local transport policy requires careful assessment of who benefits and who pays for changes before the new bus route is introduced.'};
const b={...a,id:'b',sourceText:a.sourceText.replace('bus','rail')};
assert.ok(textSimilarity(a.sourceText,b.sourceText)>.8);assert.ok(duplicateWarnings([a,b]).length);
assert.ok(duplicateWarnings([a,{...a,id:'c'}]).some(x=>x.type==='exact'));
assert.equal(checkContent({...VOCABULARY_EXERCISES[0],answer:'not an option'}).valid,false);
assert.equal(checkContent({...READING_PASSAGES[0],questions:[]}).valid,false);
assert.equal(checkContent({...READING_PASSAGES[0],questions:Array(5).fill(READING_PASSAGES[0].questions[0])}).valid,false);
assert.equal(checkContent({...READING_PASSAGES[0],sourceText:'A short text.'}).valid,false);
assert.equal(checkContent({...CLOZE_PASSAGES[0],sourceText:'There are no blanks in this passage.'}).valid,false);
assert.equal(checkContent({...EXAM_PASSAGES[0],sourceText:'太短。'}).valid,false);
assert.ok(FULL_PRACTICE_SETS.every(x=>checkFullPractice(x,EXAM_PASSAGES).valid));
assert.equal(checkFullPractice({...FULL_PRACTICE_SETS[0],directions:{'zh-en':['missing','missing'],'en-zh':[]}},EXAM_PASSAGES).valid,false);
const draft={...example,id:'draft-test',contentStatus:'draft',qualityReview:null,reviewedBy:null};
assert.ok(validateGeneratedContent(draft).valid);
assert.throws(()=>publishContent(draft));
const validated=markValidated(draft);
assert.throws(()=>publishContent(validated));
const review={reviewer:'test-fixture-only',version:validated.contentVersion,fingerprint:fingerprint(validated),notes:'Test fixture sign-off',checks:{semantic:true,answer:true,reference:true,difficulty:true,diversity:true}};
const reviewed=recordReview(validated,review);
assert.equal(publishContent(reviewed).contentStatus,'published');
assert.throws(()=>publishContent({...reviewed,sourceText:reviewed.sourceText+' changed'}));
assert.throws(()=>publishContent(reviewed,[{...example,id:'duplicate'}]));
const request={contentType:'sentence',direction:'zh-en',difficultyTier:'foundation',topic:'城市',count:1,constraints:{}};
assert.ok(validateGenerationRequest(request));assert.equal(validateGenerationRequest({...request,count:0}),false);
await assert.rejects(()=>generateContent(request),/GENERATOR_DISABLED/);
const result=await generateContent(request,{provider:{name:'test-fixture/no-network',generate:async()=>[{...example,contentStatus:'published',reviewedBy:'pretend'}]}});
assert.equal(result.items[0].contentStatus,'draft');assert.equal(result.items[0].reviewedBy,null);assert.notEqual(result.items[0].id,example.id);assert.equal(result.published,false);
await assert.rejects(()=>generateContent(request,{provider:{name:'fixture',generate:async()=>[]}}),/count mismatch/);
console.log('Content engine negative gates, lifecycle, published pool, structure, full sets, generator isolation passed');

