import assert from 'node:assert/strict';
import {SENTENCE_EXERCISES} from '../src/features/exercises/sentenceDataset.js';
import {PARAGRAPH_EXERCISES,validateParagraphDataset} from '../src/features/questionBank/paragraphDataset.js';
import {PAST_PAPERS,validatePastPapers} from '../src/features/questionBank/pastPaperDataset.js';
import {normalizeTrainingSession,calculateDurationMs} from '../src/features/training/trainingSchema.js';
import {filterExercises,canMove} from '../src/features/training/trainingSelectors.js';
import {validateExercise} from '../src/features/exercises/exerciseSchema.js';
import {readStorage,writeStorage} from '../src/storage/storageAdapter.js';
assert.equal(new Set(SENTENCE_EXERCISES.map(x=>x.id)).size,SENTENCE_EXERCISES.length);
assert.ok(SENTENCE_EXERCISES.every(validateExercise));
assert.equal(PARAGRAPH_EXERCISES.length,12); assert.ok(validateParagraphDataset()); assert.ok(PARAGRAPH_EXERCISES.every(validateExercise));
assert.ok(validatePastPapers());
const legacy=normalizeTrainingSession({source:'old',answer:'mine',reference:'ref'});
assert.equal(legacy.sourceText,'old'); assert.equal(legacy.userAnswer,'mine'); assert.equal(legacy.referenceAnswer,'ref');
assert.equal(calculateDurationMs('2026-01-01T00:00:00Z','2026-01-01T00:01:30Z'),90000);
assert.equal(filterExercises(PARAGRAPH_EXERCISES,'zh-en').length,6); assert.equal(filterExercises(PARAGRAPH_EXERCISES,'en-zh').length,6);
assert.equal(canMove(0,12,-1),false); assert.equal(canMove(0,12,1),true); assert.equal(canMove(11,12,1),false);
const map=new Map(); const fake={getItem:k=>map.has(k)?map.get(k):null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};
writeStorage('test',{ok:true},fake); assert.deepEqual(readStorage('test',null,fake),{ok:true});
console.log('core contract tests passed');
