import assert from 'node:assert/strict';
import {PAST_PAPER_SOURCE_REGISTRY as registry} from '../src/features/questionBank/sourceRegistry.js';
import {defaultVariant,filterRegistry,fullSessionExercises,isTrainable,mergeVariants,registryStats,sessionSnapshot,trainingExercise,validateSourceRegistry} from '../src/features/questionBank/sourceRegistryService.js';
import {normalizeTrainingSession} from '../src/features/training/trainingSchema.js';
import {readStorage,writeStorage} from '../src/storage/storageAdapter.js';
assert.equal(validateSourceRegistry(),true);
assert.equal(validateSourceRegistry([...registry,registry[0]]),false);
const broken=structuredClone(registry);broken[0].materials[0].variants[0].sourceURLs=['javascript:alert(1)'];assert.equal(validateSourceRegistry(broken),false);
assert.equal(registryStats().years,24);
assert.ok(registry.every(r=>r.sources.every(s=>s.evidence&&s.checkedAt)));
assert.ok(!registry.some(r=>r.month==='12'&&['2016','2017'].includes(r.year)));
const r18=registry.find(r=>r.id==='catti2-2018-11');
const allMaterials=registry.flatMap(r=>r.materials);
const imported=allMaterials.map(p=>trainingExercise(p)).filter(Boolean);
assert.equal(imported.length,registryStats().trainableItems);
const noRef=imported.find(p=>p.subject==='practical'&&!p.referenceTranslation);
assert.ok(noRef&&isTrainable(noRef));
assert.equal(trainingExercise(allMaterials.find(p=>!p.variants.some(isTrainable))),null);
const variant=defaultVariant(r18.materials.find(p=>p.direction==='zh-en'));
assert.ok(isTrainable(variant));
assert.equal(mergeVariants([variant,{...variant,id:'reprint',sourceURLs:['https://example.org/reprint']}]).length,1);
assert.equal(mergeVariants([variant,{...variant,id:'changed',sourceText:variant.sourceText+'差异'}]).length,2);
assert.equal(mergeVariants([{id:'a',sourceText:'',sourceURLs:['https://example.org/a']},{id:'b',sourceText:'',sourceURLs:['https://example.org/b']}]).length,2);
assert.equal(fullSessionExercises(r18).length,0);
assert.ok(filterRegistry(registry,{year:'2025',month:'06',subject:'practical',direction:'zh-en',query:'消博会'}).every(r=>r.year==='2025'&&r.month==='06'&&r.visibleMaterials.every(m=>m.direction==='zh-en')));
assert.equal(filterRegistry(registry,{year:'2025',month:'06',subject:'practical',direction:'zh-en',query:'消博会'}).length,1);
assert.equal(filterRegistry(registry,{year:'2025',query:'不存在的主题98765'}).length,0);
assert.ok(filterRegistry(registry,{}).length>filterRegistry(registry,{year:'2025'}).length);
const entries=new Map(),storage={getItem:k=>entries.get(k)||null,setItem:(k,v)=>entries.set(k,v)};
const drafts=imported.filter(p=>p.subject==='practical').map((p,i)=>normalizeTrainingSession({...sessionSnapshot(p,'审查作答 '+i,'2026-09-18T01:00:00Z','2026-09-18T01:01:30Z'),id:'isolated-test-'+i}));
assert.notEqual(drafts[0].sourceText,drafts[1].sourceText);
assert.notEqual(drafts[0].exerciseId,drafts[1].exerciseId);
assert.ok(drafts.some(s=>s.referenceAnswer===null));
assert.equal(drafts[0].durationMs,90000);
assert.equal(drafts[0].exerciseType,'past-paper');
assert.equal(drafts[0].sourceType,'past-paper');
writeStorage('isolated-registry-test',drafts,storage);
assert.deepEqual(readStorage('isolated-registry-test',[],storage),drafts);
assert.throws(()=>sessionSnapshot(imported[0],'  ','2026-09-18T00:00:00Z'));
console.log('Public archive: evidence schema, filters, variants, missing reference, distinct snapshots and isolated persistence PASS');

