import assert from 'node:assert/strict';
import fs from 'node:fs';
import {browserHarness} from './browserHarness.mjs';
import {GRAMMAR_EXERCISES,READING_PASSAGES,CLOZE_PASSAGES} from '../src/features/comprehensive/comprehensiveDataset.js';
import {COMPREHENSIVE_SIMULATIONS} from '../src/features/simulation/comprehensiveSimulations.js';
const b=await browserHarness();const {page,wait,evaluate,click,button,contains}=b;const result={};
const text=()=>evaluate('document.body.innerText');const sessions=()=>evaluate("JSON.parse(localStorage.getItem('catti.trainingSessions')||'[]')");
const home=()=>click(contains('01首页'));
const enterTranslation=async level=>{await home();await click(contains('翻译实务Sentence'));await click(contains('Level '+level));};
const type=async(selector,value)=>{await click(`document.querySelector(${JSON.stringify(selector)})`);await page.send('Input.insertText',{text:value});await wait()};
const comp=async label=>{await home();await click(contains('综合能力Vocabulary'));await click(contains(label));};
const shot=async name=>{const {data}=await page.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync('docs/training-rebuild/'+name+'.png',Buffer.from(data,'base64'))};
fs.mkdirSync('docs/training-rebuild',{recursive:true});
try{
 await page.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await enterTranslation(1);assert.ok((await text()).includes('建议 12 min'));await type('#sentence-answer','浏览器真实输入 Sentence 测试\nSecond line.');await wait(1100);await click(button('获取提示'));await click(button('查看参考'));await click(button('提交答案'));assert.ok((await text()).includes('YOUR VERSION'));let ss=await sessions();assert.equal(ss[0].exerciseType,'sentence');assert.ok(ss[0].sourceText.length>60);assert.ok(ss[0].contentVersion);await click(button('← 返回翻译实务'));result.flow1='PASS';
 await click(contains('Level 2'));await type('#paragraph-answer','段落草稿测试\nDraft survives navigation.');const src=await evaluate("document.querySelector('.source-text').textContent");await click(button('← 返回翻译实务'));await click(contains('Level 2'));assert.equal(await evaluate("document.querySelector('textarea').value"),'段落草稿测试\nDraft survives navigation.');await click(button('提交答案'));assert.ok((await text()).includes('段落草稿测试'));ss=await sessions();assert.equal(ss[0].sourceText,src);assert.equal(ss[0].exerciseType,'paragraph');result.flow2='PASS';
 await enterTranslation(3);await type('#exam-passage-answer','Exam Passage browser answer.');await wait(1100);await click(button('暂停'));const t=await evaluate("document.querySelector('.training-timer strong').textContent");await wait(1300);assert.equal(await evaluate("document.querySelector('.training-timer strong').textContent"),t);await click(button('继续'));await click(button('提交并保存'));ss=await sessions();assert.equal(ss[0].exerciseType,'exam-passage');assert.ok(ss[0].durationMs>0);await home();await click(button('学习记录 →'));assert.ok((await text()).includes(ss[0].topic));await click("document.querySelector('.record-card')");assert.ok((await text()).includes('Exam Passage browser answer.'));result.flow3='PASS';
 await home();await click(contains('03题库'));await click(`(()=>{const s=[...document.querySelectorAll('.archive-session>summary')].find(e=>e.textContent.includes('2021.06'));return s})()`);const material=`[...document.querySelectorAll('.archive-session[open] .archive-material')].find(m=>m.textContent.includes('英译汉')&&m.querySelector('button:not(:disabled)'))`;await click(`${material}.querySelector('button:not(:disabled)')`);assert.ok((await text()).includes('2021'));assert.ok(!(await text()).includes('统一 180'));await type('#public-paper-answer','PDF recovered passage browser answer.');await click(button('提交并保存记录'));ss=await sessions();assert.equal(ss[0].exerciseType,'past-paper');assert.ok(ss[0].exerciseId.includes('pdf'));await click(button('← 返回真题题库'));result.flow4='PASS';
 await comp('语法专项');const g=GRAMMAR_EXERCISES[0];const wrong=g.options.find(x=>x!==g.answer);await click(`[...document.querySelectorAll('.choice-list label')].find(e=>e.textContent.trim()===${JSON.stringify(wrong)})`);await click(button('提交答案'));assert.ok((await text()).includes('回答错误'));assert.ok((await text()).includes(g.answer));assert.ok((await text()).includes(g.explanation));await click(button('← 返回综合能力'));result.flow5='PASS';
 await comp('阅读理解');assert.equal(await evaluate("getComputedStyle(document.querySelector('.exam-split')).display"),'grid');await shot('reading-desktop');const rq=READING_PASSAGES[0].questions;
 for(const q of rq)await click(`[...document.querySelectorAll('input[type=radio]')].find(e=>e.name===${JSON.stringify(q.id)}&&e.parentElement.textContent.includes(${JSON.stringify(q.answer)}))`);
 await click(button('提交整篇'));assert.ok((await text()).includes('5 / 5 正确'));ss=await sessions();assert.equal(ss.filter(s=>rq.some(q=>q.id===s.exerciseId)).length,5);await click(button('← 返回综合能力'));result.flow6='PASS';
 await comp('完形 / 语言运用');const cq=CLOZE_PASSAGES[0].blanks;
 await click(contains('Blank 8'));assert.equal(await evaluate("document.querySelector('mark.active').textContent.trim()"),'(8) ___');
 for(const q of cq)await click(`[...document.querySelectorAll('input[type=radio]')].find(e=>e.name===${JSON.stringify(q.id)}&&e.parentElement.textContent.includes(${JSON.stringify(q.answer)}))`);
 await click(button('提交整篇'));assert.ok((await text()).includes('10 / 10 正确'));ss=await sessions();assert.equal(ss.filter(s=>cq.some(q=>q.id===s.exerciseId)).length,10);result.flow7='PASS';
 await page.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await wait();assert.ok(await evaluate('document.documentElement.scrollWidth<=390'));await shot('cloze-mobile');await click(contains('题目 ·'));assert.equal(await evaluate("getComputedStyle(document.querySelector('.split-questions')).display"),'block');await shot('cloze-mobile-answers');result.mobile390='PASS';await page.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await home();await click(contains('整套模拟按'));await click(contains('笔译实务整套模拟'));assert.equal(await evaluate("document.querySelectorAll('.hub-row').length"),5);assert.equal(await evaluate("document.querySelectorAll('.training-timer').length"),0);await click("document.querySelector('.hub-row')");const before=(await sessions()).length;assert.ok((await text()).includes('建议 180 min'));
 for(let i=0;i<4;i++){await click(`document.querySelectorAll('.paragraph-tabs button')[${i}]`);assert.equal(await evaluate("document.querySelector('textarea').value"),'');await type('#full-practice-answer','Full set independent answer '+i);}
 await click("document.querySelectorAll('.paragraph-tabs button')[0]");assert.equal(await evaluate("document.querySelector('textarea').value"),'Full set independent answer 0');await click(button('← 返回整套模拟列表'));await click("document.querySelector('.hub-row')");assert.equal(await evaluate("document.querySelector('textarea').value"),'Full set independent answer 0');await click(button('提交整套训练'));ss=await sessions();assert.equal(ss.length,before+4);const batch=ss.slice(0,4);assert.equal(new Set(batch.map(s=>s.sourceText)).size,4);assert.equal(new Set(batch.map(s=>s.userAnswer)).size,4);assert.ok(batch.every(s=>s.paperId===batch[0].paperId));result.flow8='PASS';
 await home();await click(contains('整套模拟按'));await click(contains('综合能力整套模拟'));assert.equal(await evaluate("document.querySelectorAll('.hub-row').length"),3);await click("document.querySelectorAll('.hub-row')[1]");assert.ok((await text()).includes('建议 120 min'));const set=COMPREHENSIVE_SIMULATIONS[1];
 for(const section of set.sections){await click(contains(section.title));for(let index=0;index<section.items.length;index++){const item=section.items[index];if(item.questions||item.blanks){for(const q of item.questions||item.blanks)await click(`[...document.querySelectorAll('input[type=radio]')].find(e=>e.name===${JSON.stringify(q.id)}&&e.parentElement.textContent.includes(${JSON.stringify(q.answer)}))`);}else{await click(`[...document.querySelectorAll('.choice-list label')].find(e=>e.textContent.trim()===${JSON.stringify(item.answer)})`);if(index<section.items.length-1)await click(button('下一题'));}}await click(button('提交本节并保存'));assert.ok((await text()).includes('本节已保存'));}
 await click(button('提交整套模拟'));ss=await sessions();assert.equal(ss.filter(s=>s.paperId===set.id).length,35);result.flow9='PASS';
 const expected=ss.length;await page.send('Page.reload');await wait(900);assert.equal((await sessions()).length,expected);await click(contains('整套模拟按'));await click(contains('综合能力整套模拟'));await click("document.querySelectorAll('.hub-row')[1]");assert.ok((await text()).includes('本节已保存'));assert.equal(await evaluate("[...document.querySelectorAll('button')].find(e=>e.textContent==='提交整套模拟').disabled"),true);result.refreshPersistence='PASS';
 result.runtimeErrors=page.events.filter(e=>e.method==='Runtime.exceptionThrown');assert.equal(result.runtimeErrors.length,0);
 result.status='PASS';console.log(JSON.stringify(result,null,2));
}catch(e){result.status='FAIL';result.error=e.stack;console.error(e);await shot('failure');console.error((await text()).slice(-2500));process.exitCode=1;}finally{fs.writeFileSync('docs/training-rebuild/browser-qa.json',JSON.stringify(result,null,2));await b.close()}
