import assert from 'node:assert/strict';import fs from 'node:fs';import {browserHarness} from './browserHarness.mjs';import {READING_PASSAGES,CLOZE_PASSAGES} from '../src/features/comprehensive/comprehensiveDataset.js';
const b=await browserHarness(),{page,evaluate,click,button,contains,wait}=b,result={};const text=()=>evaluate('document.body.innerText'),ss=()=>evaluate("JSON.parse(localStorage.getItem('catti.trainingSessions')||'[]')");const nav=async id=>{await evaluate('window.dispatchEvent(new CustomEvent("catti:navigate",{detail:'+JSON.stringify(id)+'}))');await wait()};const type=async(sel,value)=>{await click('document.querySelector('+JSON.stringify(sel)+')');await page.send('Input.insertText',{text:value});await wait()};const back=()=>click('document.querySelector("button[aria-label=返回上一层]")');const timer=()=>evaluate("Object.values(JSON.parse(localStorage.getItem('catti.trainingTimers')||'{}')).find(s=>s.running)");const shot=async name=>{const {data}=await page.send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('docs/workspace-consolidation/'+name+'.png',Buffer.from(data,'base64'))};
try{
 await page.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await nav('practical');await click(contains('Level 2'));assert.equal(await evaluate("getComputedStyle(document.querySelector('.translation-workspace')).display"),'grid');assert.ok((await text()).includes('尚未开始'));await wait(1100);assert.equal(await timer(),undefined);await type('#paragraph-answer','真实中文输入 abc\nParagraph draft.');assert.equal((await timer()).timerStartTrigger,'first-input');assert.ok((await text()).includes('已开始记录本次训练时间'));await wait(1100);await click(button('暂停'));const frozen=await evaluate("document.querySelector('.training-timer strong').textContent");await wait(1300);assert.equal(await evaluate("document.querySelector('.training-timer strong').textContent"),frozen);await click(button('保存草稿'));await shot('paragraph-desktop');await back();await click(contains('Level 2'));assert.equal(await evaluate("document.querySelector('textarea').value"),'真实中文输入 abc\nParagraph draft.');assert.ok((await text()).includes('已暂停'));await click(button('继续'));await wait(1100);await click(button('提交翻译'));let records=await ss();assert.ok(records[0].activeDurationMs>1000);assert.ok(records[0].pauseDurationMs>=1000);assert.ok(records[0].timerStartedAt);assert.equal(records[0].timerStartTrigger,'first-input');result.paragraph='PASS';result.timerPauseDraftResume='PASS';
 await nav('exam-passage');assert.ok((await text()).includes('建议 45 min'));assert.ok((await text()).includes('不代表官方'));assert.ok((await text()).includes('尚未开始'));await click(button('开始计时'));assert.equal((await timer()).timerStartTrigger,'manual');await type('#exam-passage-answer','Manual reading time followed by translation.');await wait(1000);await click(button('提交翻译'));assert.equal((await ss())[0].timerStartTrigger,'manual');result.manualStart='PASS';await nav('practical');
 // Deterministic overtime fixture in an isolated browser, no real user storage.
 await evaluate("(()=>{const k='catti.trainingTimers',d=JSON.parse(localStorage.getItem(k));const id=Object.keys(d).find(k=>k.includes('exam'));d[id]={...d[id],finished:false,finishedAt:null,running:false,activeDurationMs:2701000,timerStartedAt:new Date(Date.now()-2702000).toISOString(),lastUpdated:Date.now()};localStorage.setItem(k,JSON.stringify(d))})()");await nav('exam-passage');assert.ok((await text()).includes('超时'));await click(button('继续'));await wait(1300);await click(button('提交翻译'));records=await ss();assert.ok(records[0].activeDurationMs>2702000);assert.equal(records[0].recommendedDurationMs,2700000);assert.equal(records[0].overtimeMs,records[0].activeDurationMs-2700000);result.examOvertime='PASS';
 await nav('questions');assert.equal(await evaluate("document.querySelectorAll('.archive-material button:disabled').length"),0);assert.equal(await evaluate("document.querySelectorAll('.archive-material').length"),39);assert.equal(await evaluate("[...document.querySelectorAll('.archive-material h5')].filter(x=>x.textContent.includes('Passage')).length"),37);result.trainableVisible=37;
 await click(contains('全部资料'));assert.ok(await evaluate("document.querySelectorAll('.archive-material button:disabled').length>0"));await click(contains('可训练 39'));
 await click("[...document.querySelectorAll('.archive-session>summary')].find(e=>e.textContent.includes('2021.06'))");await click("[...document.querySelectorAll('.archive-session[open] .archive-material')].find(m=>m.textContent.includes('英译汉')&&m.querySelector('button:not(:disabled)')).querySelector('button:not(:disabled)')");assert.ok(await evaluate("!!document.querySelector('.translation-workspace')"));assert.ok((await text()).includes('尚未开始'));await type('#public-paper-answer','PDF recovered source translation.');await click(button('提交并保存记录'));records=await ss();assert.ok(records[0].exerciseId.includes('pdf'));assert.equal(records[0].exerciseType,'past-paper');await back();assert.ok(await evaluate("!!document.querySelector('.archive-availability')"));result.pastPaper='PASS';
 for(const mode of ['reading','cloze']){await nav(mode);assert.equal(await evaluate("getComputedStyle(document.querySelector('.exam-split')).display"),'grid');assert.ok((await text()).includes('尚未开始'));if(mode==='cloze'){await click(contains('Blank 8'));assert.equal(await evaluate("document.querySelector('mark.active').textContent.trim()"),'(8) ___');assert.equal(await timer(),undefined)}const qs=mode==='reading'?READING_PASSAGES[0].questions:CLOZE_PASSAGES[0].blanks;for(const q of qs)await click('[...document.querySelectorAll("input[type=radio]")].find(e=>e.name==='+JSON.stringify(q.id)+'&&e.parentElement.textContent.includes('+JSON.stringify(q.answer)+'))');await click(button('提交整篇'));const saved=(await ss()).filter(s=>qs.some(q=>q.id===s.exerciseId));assert.equal(saved.length,qs.length);assert.ok(saved.every(s=>s.timerStartTrigger==='first-input'));result[mode]='PASS';}
 await nav('comprehensive-hub');await click("document.querySelector('.breadcrumbs button')");assert.ok((await text()).includes('翻译实务'));result.breadcrumb='PASS';await nav('reading');await back();assert.ok((await text()).includes('词汇专项'));result.focusBack='PASS';
 await nav('full-practice');await click("document.querySelector('.hub-row')");assert.ok((await text()).includes('尚未开始'));for(let i=0;i<4;i++){await click('document.querySelectorAll(".paragraph-tabs button")['+i+']');await type('#full-practice-answer','Independent full practice answer '+i);await wait(400)}await click(button('提交整套训练'));const full=(await ss()).slice(0,4);assert.equal(full.reduce((a,s)=>a+s.activeDurationMs,0),full[0].groupActiveDurationMs);assert.ok(full.every(s=>s.recommendedDurationMs===10800000));result.fullSharedTimer='PASS';
 await page.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});result.mobile={};for(const id of ['paragraph','exam-passage','questions','reading','cloze','records']){await nav(id);assert.ok(await evaluate('document.documentElement.scrollWidth<=390'),id+' overflow');result.mobile[id]='PASS';if(id==='paragraph')await shot('paragraph-mobile');}
 await nav('records');await click('document.querySelector(".record-card")');assert.ok((await text()).includes('训练详情'));assert.equal(await evaluate("document.querySelector('.breadcrumbs [aria-current]').tagName"),'SPAN');await click(button('学习记录'));assert.ok(!(await text()).includes('训练详情'));result.recordBreadcrumb='PASS';
 const before=(await ss()).length;await page.send('Page.reload');await wait(800);assert.equal((await ss()).length,before);result.persistence='PASS';result.runtimeErrors=page.events.filter(e=>e.method==='Runtime.exceptionThrown').length;assert.equal(result.runtimeErrors,0);console.log(result);
}catch(error){result.error=error.stack;console.log(await text());throw error}finally{fs.writeFileSync('docs/workspace-consolidation/browser-qa.json',JSON.stringify(result,null,2));await b.close()}
