// Government white-paper / public policy speech extracts. Exam association is a
// public compilation claim, NOT an official examination or official answer claim.
export const TCM_TEXT = '人类在漫长发展进程中创造了丰富多彩的世界文明，中华文明是世界文明多样性、多元化的重要组成部分。中医药作为中华文明的杰出代表，是中国各族人民在几千年生产生活实践和与疾病作斗争中逐步形成并不断丰富发展的医学科学，不仅为中华民族繁衍昌盛作出了卓越贡献，也对世界文明进步产生了积极影响。\n\n中医药在历史发展进程中，兼容并蓄、创新开放，形成了独特的生命观、健康观、疾病观、防治观，实现了自然科学与人文科学的融合和统一，蕴含了中华民族深邃的哲学思想。随着人们健康观念变化和医学模式转变，中医药越来越显示出独特价值。中医药与西医药优势互补，相互促进，共同维护和增进民众健康，已经成为中国医疗卫生体制的重要特征和显著优势。';
export const TCM_REFERENCE = 'Humanity has created a colorful global civilization in the long course of its development, and the civilization of China is an important component of the world civilization harboring great diversity. As a representative feature of Chinese civilization, traditional Chinese medicine (TCM) is a medical science that was formed and developed in the daily life of the people and in the process of their fight against diseases over thousands of years. It has made a great contribution to the nation’s procreation and the country’s prosperity, in addition to producing a positive impact on the progress of human civilization.\n\nTCM has created unique views on life, on fitness, on diseases and on the prevention and treatment of diseases during its long history of absorption and innovation. It represents a combination of natural sciences and humanities, embracing profound philosophical ideas of the Chinese nation. As ideas on fitness and medical models change and evolve, traditional Chinese medicine has come to underline a more and more profound value. TCM and Western medicine have their different strengths. They work together in China to protect people from diseases and improve public health. This has turned out to be one of the important features and notable strengths of medicine with Chinese characteristics.';
export const FOOD_TEXT = '人人有饭吃，是人类最基本的生存权利，是一切人权的基础。全球农业发展取得了长足的进步，但饥饿和贫困依然是一种“无声的危机”，困扰着全人类。目前世界上还有8亿多贫困人口面临着食物不足、营养不良的威胁。促进农业发展，消除饥饿和贫困，依然是世界面临的重大挑战，也是全人类肩负的共同责任。国际社会应当携起手来，加强农业合作，更多关注发展中国家、尤其是一些最不发达国家的诉求。应减少贸易保护，加强对最不发达国家农业技术、资金等支持，提高全球农业生产水平和粮食安全保障水平。\n\n中国作为世界上最大的发展中国家，任何时候都是维护世界粮食安全的积极力量。尽管中国农业进一步发展面临不少困难，但我们仍将不懈努力，用行动来兑现诺言，主要依靠自己的力量解决好吃饭问题。我们愿与世界各国携手奋进，共同创造一个无饥饿、无贫困、可持续发展的世界。';
export const PUBLIC_VOCAB_ITEM = {
  sourceText:'All the students of this university have free ________ to the Internet via a broadband connection.',
  options:['access','entrance','permission','passageway'], answer:'access',
  referenceTranslation:'A · access', originalNumber:1,
};
