export const REBUILD_PARAGRAPHS=[
['zh-en','教育资格互认',`跨地区承认职业资格，看似只是把几张证书列入共同目录，实际却涉及培训内容、实习条件和责任制度之间的差异。同一职业名称下，有的地区允许从业者独立提供服务，有的则要求在监督下工作。如果互认只核对名称，而不说明能力范围，消费者就可能误以为资格相同意味着服务保障完全一致。增加补充考试并非唯一办法。监管者可以比较核心任务，认可已经证明的能力，并把培训集中于当地规则与明显缺口，避免要求有经验者从头学习。与此同时，对申请人的语言要求应当与实际工作需要相关，不能以提高安全为名设置无关障碍。互认的目的不是取消所有差异，而是让必要差异变得可说明、可补足。只有提供清楚的申诉程序，并公布评估依据，制度才可能既保护公众，又不把职业流动变成只有资金充裕者才能跨越的门槛。`, `Recognising occupational qualifications across regions may appear to be a matter of listing certificates in a common catalogue, but it involves differences in training, practical experience and systems of responsibility. Under the same occupational title, one region may allow practitioners to work independently while another requires supervision. If recognition checks only names without explaining the scope of competence, consumers may assume that identical qualifications offer identical protection. Additional examinations are not the only solution. Regulators can compare core tasks, recognise demonstrated competence and concentrate training on local rules and evident gaps, rather than making experienced practitioners start again. Language requirements must meanwhile relate to actual work and must not impose irrelevant barriers in the name of safety. Recognition is intended not to eliminate every difference but to make necessary differences explainable and remediable. Only clear appeal procedures and published assessment criteria can enable the system to protect the public without turning occupational mobility into a threshold that only those with ample resources can cross.`, '职业名称与能力范围；not…the only否定范围；保障与准入双重目标。'],
['zh-en','生态修复与时间',`判断矿区修复是否成功，不能只看验收时的植被覆盖率。生长迅速的外来草种可能很快使裸地变绿，却消耗更多水分，挤压本地植物恢复的空间。短期景观改善与长期生态功能并不必然一致。企业退出之后，谁负责监测土壤污染、维护排水设施并承担后续费用，也必须在工程开始前说清。把责任交给地方政府而不同时提供资金，只是把企业成本转移为公共负担。修复保证金可以减少这种风险，但金额若长期不随实际成本调整，保障就可能只停留在纸面。更可靠的安排应允许根据监测结果分阶段释放资金，而不是在一次验收后全部退还。这并不意味着要求企业对所有自然变化无限负责，而是要求区分可预见的修复义务与不可控制的外部变化，并使相关判断接受独立复核。恢复一片土地的价值，最终还应由它能否支持持续的生活与生产来检验。`, `Success in rehabilitating a mining site cannot be judged solely by vegetation cover at acceptance. Fast-growing non-native grasses may quickly turn bare ground green while consuming more water and reducing the space available for native plants to recover. Short-term improvements in appearance do not necessarily restore long-term ecological functions. Before work begins, it must also be clear who will monitor soil contamination, maintain drainage and bear subsequent costs after the company leaves. Assigning responsibility to local government without funding merely transfers corporate costs to the public. Rehabilitation bonds can reduce that risk, but protection may remain nominal if their value is not adjusted to actual costs. A more reliable arrangement would release funds in stages according to monitoring results rather than return everything after a single inspection. This does not require companies to bear unlimited responsibility for every natural change. It requires foreseeable rehabilitation obligations to be distinguished from uncontrollable external changes, with independent review of those judgments. The value of restoring land must ultimately also be tested by its capacity to sustain life and production.`, '验收时点与长期功能；保证金和责任边界；短期绿化不等于生态恢复。'],
['zh-en','出版与公共知识',`公共资助的研究改为开放出版后，读者不再支付下载费用，但知识传播的成本并未消失，只是可能转移到作者一端。对经费充足的机构，论文处理费是一项预算支出；对缺乏稳定资助的研究者，它却可能成为发表成果的障碍。因此，以免费阅读作为公平的唯一指标，会忽视谁有能力进入公开讨论。统一减免费用能够缓解困难，但若审批标准不透明，申请者仍可能承担无法预估的风险。图书馆、资助机构与出版者可以协商集体支付安排，却应避免把大型机构的谈判能力变成新的准入门槛。评价出版模式时，既要看公众能否接触研究，也要看不同地区与学科的作者能否被听见。开放不只是移除一道付费墙，还涉及编辑劳动由谁承担、审稿质量如何维持，以及那些商业价值有限但学术意义重要的成果，能否获得稳定的传播空间。`, `When publicly funded research moves to open publishing, readers no longer pay to download it, but dissemination costs do not disappear; they may shift to authors. For well-funded institutions, article-processing charges are a budget item. For researchers without stable support, they can become a barrier to publication. Treating free reading as the sole measure of fairness therefore overlooks who can enter public debate. Fee waivers can alleviate the difficulty, but opaque approval criteria may still expose applicants to unpredictable risks. Libraries, funders and publishers can negotiate collective payment arrangements, but should avoid making large institutions' bargaining power a new barrier to entry. Publishing models should be assessed not only by whether the public can access research but also by whether authors from different regions and disciplines can be heard. Openness involves more than removing a paywall: it concerns who bears the work of editing, how peer-review quality is maintained and whether findings with limited commercial appeal but significant scholarly value have stable channels of dissemination.`, '成本转移而非消失；免费阅读与发表公平；who/how/whether并列。'],
['zh-en','城市夜间劳动',`城市夜间经济常以灯光、客流和营业收入来呈现，但维持其运转的人并不都分享同样的收益。餐饮与配送从业者下班时，公共交通可能已经停运，白天可使用的托育服务也无法覆盖夜班。若政策只补贴延长营业时间，却不考虑这些配套条件，新增成本就可能由收入最低、议价能力最弱的人承担。夜间服务不宜简单复制白天的安排：客流分散意味着固定线路未必适用，而灵活接驳又需要明确安全标准和支付方式。居民对噪声的异议也不能一概视为阻碍发展，其中既有利益冲突，也有真正的健康负担。协商应当让经营者、劳动者与居民都能提出证据，并定期调整营业与服务规则。一个有活力的夜间城市，不应只让消费者拥有更多选择，还应让提供服务的人能够安全回家、安排照护，并对自己的劳动时间保有一定的决定权。`, `Urban night-time economies are often portrayed through lighting, footfall and sales, but those who keep them running do not share equally in the gains. When catering and delivery workers finish, public transport may have stopped, and daytime childcare cannot cover night shifts. If policy subsidises longer opening hours without considering supporting services, additional costs may fall on those with the lowest incomes and weakest bargaining power. Night services should not simply reproduce daytime arrangements: dispersed demand may make fixed routes unsuitable, while flexible connections require clear safety standards and payment systems. Nor can residents' objections to noise all be dismissed as resistance to development; they involve both competing interests and genuine health burdens. Negotiations should enable businesses, workers and residents to present evidence, with operating and service rules adjusted regularly. A vibrant night-time city should not merely expand consumers' choices. It should also enable service workers to travel home safely, arrange care and retain some control over their working hours.`, '夜间经济的隐性劳动成本；利益冲突不否定健康诉求；末句主语与并列动词。'],
['en-zh','农业技术与适应',`A seed variety developed to withstand drought may perform well in a controlled trial and still disappoint the farmers encouraged to adopt it. The trial may assume timely access to fertiliser, reliable storage and a planting date that households cannot observe when they depend on shared machinery. Describing the gap as resistance to innovation would confuse a failure of supporting arrangements with an unwillingness to learn.

Farmers also judge risk differently from researchers reporting average yields. A variety that produces more in most seasons but fails badly in an unusual one may be unattractive to a household unable to survive a single lost harvest. The relevant comparison is therefore not simply between old and new technology. It concerns the distribution of possible outcomes and the resources available when things go wrong. A higher expected return does not necessarily make a choice affordable.

Demonstration projects can address these concerns if they allow farmers to test varieties on a limited area and compare results under ordinary working conditions. They are less informative when exceptional subsidies or intensive assistance are withdrawn as soon as the demonstration ends. Apparent success may then reflect support that is unavailable to subsequent adopters rather than the qualities of the seed itself.

Public agencies should consequently disclose the conditions under which their estimates were obtained and avoid presenting adoption rates as a sufficient measure of progress. Information about who stopped using a variety, and why, may be as valuable as evidence that others continued. Treating withdrawal as feedback rather than disobedience makes it possible to improve a programme without requiring farmers to bear the cost of defending an official success story.`, `一种为抗旱而培育的种子，可能在受控试验中表现良好，却令被鼓励采用它的农民失望。试验可能假定化肥能及时获得、储存可靠，并设定了依赖共用机械的家庭无法遵守的播种日期。把这种差距称为抗拒创新，会混淆配套安排失效与不愿学习。

农民判断风险的方式，也不同于报告平均产量的研究者。某品种大多数年份产量较高，却在异常年份严重减产，对于承受不起一次绝收的家庭，可能没有吸引力。因此，需要比较的不只是新旧技术，还包括可能结果的分布，以及出问题时可用的资源。较高的预期收益，不一定使选择变得可负担。

如果示范项目允许农民在小面积土地试种，并在日常作业条件下比较结果，就能回应这些顾虑。若特殊补贴或密集协助在示范结束后立即撤走，项目的信息价值就较低。表面成功可能反映后续采用者无法得到的支持，而非种子本身的特点。

因此，公共机构应说明估计结果的取得条件，不把采用率视为进步的充分指标。谁停止使用某品种及其原因，可能与其他人继续使用的证据同样有价值。把退出视为反馈而非不服从，才能改进项目，而不要求农民承担维护官方成功叙事的成本。`, '受控实验与实际条件；平均收益与尾部风险；withdrawal反馈而非不服从。'],
['en-zh','外交与翻译',`Diplomatic agreements are sometimes praised for language flexible enough to secure unanimous support. Flexibility can indeed make cooperation possible when participants cannot accept an explicit statement of their differences. Yet an expression that postpones disagreement at the negotiating table may transfer it to the officials later responsible for implementation. Agreement on a text is not necessarily agreement on the obligations it creates.

Translation makes this problem visible, but does not always cause it. Where several language versions are equally authoritative, interpreters must consider the instrument as a whole rather than assume that one version contains the original meaning and the others merely reproduce it. A term referring to consultation may imply a duty to exchange information without conferring a right to withhold consent. Rendering it as approval would silently alter the allocation of authority.

Historical context matters too. A phrase adopted to accommodate a specific reservation may acquire a broader meaning when quoted without the accompanying records. Those records cannot automatically override the agreed text, but they may help explain why a seemingly awkward distinction was retained. Improving fluency by removing that distinction can therefore make a translation less accurate even when it reads more naturally.

For this reason, responsible revision requires more than comparing dictionaries. Translators need to identify the actions each party is entitled or required to take, the conditions limiting those actions and the procedure for resolving disputes. Where the text leaves a question genuinely open, the translation should preserve that uncertainty rather than settle it on behalf of the negotiators. Clarity is valuable, but it must not be purchased by inventing a consensus the parties never reached.`, `外交协议有时因措辞灵活、足以获得一致支持而受到称赞。当参与方不能接受明确写出分歧时，灵活性确能使合作成为可能。然而，在谈判桌上推迟分歧的表达，也可能把分歧转交给日后负责执行的官员。就文本达成一致，并不一定意味着对其产生的义务也一致。

翻译使这个问题显现，却不一定是问题的成因。当多个语言版本具有同等效力时，解释者必须考察文件整体，而不能假定一个版本包含原意，其他版本只是复制。表示协商的术语，可能意味着交换信息的义务，却不赋予拒绝同意的权利。将其译为批准，会悄然改变权力分配。

历史背景同样重要。为照顾某项具体保留而采用的措辞，一旦脱离相关记录被引用，可能获得更广含义。记录不能自动凌驾于商定文本，却可能解释为何保留一个看似别扭的区别。为提高流畅度而删除区别，因此可能使翻译虽更自然，却不够准确。

所以，负责任的修订不只是比较字典。译者需要识别各方有权或有义务采取的行动、限制行动的条件，以及解决争端的程序。如果文本确实未解决某个问题，翻译就应保留这种不确定性，而不是替谈判者作决定。清楚固然重要，却不能靠虚构各方从未达成的共识来实现。`, '同等效力版本无唯一原意；consultation/approval；entitled/required；流畅与法律范围。'],
['en-zh','博物馆与数字访问',`Putting a collection online can expand access without making that access equal. A high-resolution image allows a distant researcher to inspect details that a printed catalogue would conceal. It does little for someone without a stable connection, and it may omit the back of an object, its weight or the marks left by repeated handling. Digital availability should therefore be understood as a particular form of access rather than a complete substitute for physical examination.

The choices behind an online catalogue also affect what can be found. Objects with established names and extensive descriptions are easier to search for than those recorded under unfamiliar terms or assigned to broad residual categories. If a museum measures public interest only through search traffic, it may conclude that poorly described material is unimportant, when the catalogue itself has made that material difficult to discover.

One response is to invite users to contribute descriptions. Such participation can recover knowledge that institutional records missed, but it does not remove the need for editorial judgment. Conflicting accounts should remain distinguishable, and contributors should understand how their words will be attributed and reused. A system that silently absorbs unpaid contributions into an institutional voice may reproduce the inequality it was meant to correct.

The practical challenge is thus to maintain both openness and a record of decisions. Users need to know whether a description is an established identification, a community interpretation or a provisional suggestion. Preserving those distinctions can make a catalogue look less uniform. It also makes the collection more useful, because disagreement becomes evidence that can be investigated rather than an inconvenience removed from view.`, `把收藏放到网上，可以扩大访问，却不会使访问机会平等。高分辨率图像使远方研究者看到印刷目录掩盖的细节，却无助于网络不稳定的人，也可能省略物件背面、重量或反复触摸留下的痕迹。因此，数字可用性应被理解为一种特定访问方式，而非实物检查的完全替代。

在线目录背后的选择也影响哪些内容能被找到。名称确定、描述充分的物件，比记录在陌生术语下或归入宽泛剩余类别的物件更容易检索。如果博物馆只用搜索流量衡量公众兴趣，就可能认为描述不足的材料不重要，实际上是目录本身使其难以发现。

一种办法是邀请用户补充描述。这能找回机构记录遗漏的知识，却不能取消编辑判断。冲突叙述应保持可区分，贡献者也应了解其文字如何署名和再使用。系统若把无偿贡献悄然吸收为机构自己的声音，可能重现其本欲纠正的不平等。

实际挑战因此在于同时保持开放与决策记录。用户需要知道某项描述是确定的鉴定、社群解释，还是暂定建议。保留这些区别可能使目录不那么统一，却也更有用，因为分歧成为可调查的证据，而不是从视野中移除的麻烦。`, '数字可用不等于平等可达；检索偏差的内生循环；社群解释与机构署名。'],
['en-zh','商业统计与生产率',`When a company reports that productivity has risen after introducing new software, the result may be accurate within the boundaries of its accounts. Tasks once performed by employees may now be completed by customers: entering information, checking orders and resolving routine errors. The firm records fewer paid hours for the same sales, but the total time required to obtain the service may not have fallen. A transfer of work has been counted as an improvement in efficiency.

This does not mean that self-service is always undesirable. Some customers value the ability to act without waiting for an employee, and a well-designed system can reduce errors. The difficulty arises when a benefit experienced by confident users is assumed to apply to everyone. People who need assistance may spend longer navigating menus than they previously spent speaking to staff, while the disappearance of alternative channels leaves their additional effort unrecorded.

Comparisons between firms can be similarly misleading. One business may employ workers directly, while another purchases the same services from contractors. Their reported output per employee will differ even if the underlying process is identical. Outsourcing can make the boundary of the firm change faster than the efficiency of production. Without adjusting for that boundary, a ranking may reward accounting choices rather than operational improvement.

A useful assessment should therefore state whose time and resources are being measured and identify where costs have moved. This is more demanding than publishing a single ratio, but it prevents a narrow measure from carrying a broader claim than the evidence supports. The question is not whether the number is false; it is whether the interpretation attached to it remains valid once activities outside the accounting boundary are taken into consideration.`, `企业报告引进新软件后生产率提高，在其会计核算范围内可能准确。原由员工完成的录入信息、核查订单和处理常见错误等任务，可能转由顾客完成。企业以较少付薪工时实现相同销售额，但获得服务所需的总时间未必减少。工作转移被计作了效率提高。

这不意味着自助服务总不可取。有些顾客重视无需等待员工便可操作，良好设计也能减少错误。困难在于把熟练用户体验到的利益推定适用于所有人。需要帮助者浏览菜单的时间，可能比过去与员工交谈更长；替代渠道消失，又使额外付出未被记录。

企业间比较同样可能误导。一家直接雇人，另一家向承包商购买同样服务，即使底层流程相同，报告的人均产出也不同。外包改变企业边界的速度，可能快于生产效率的变化。不调整这一边界，排名就可能奖励会计选择而非运营改进。

因此，有价值的评估应说明衡量谁的时间和资源，并指出成本转移到哪里。这比公布单一比率更费力，却能防止狭窄指标承载超出证据的宽泛主张。问题不在于数字是否虚假，而在于把会计边界外的活动纳入考量之后，赋予数字的解释是否仍成立。`, '劳动转移与效率提升；会计边界的分母效应；数字准确不等于解释有效。']
];
