// Publicly recoverable bilingual passages. These are public compilation
// materials, not official examination answers.
export const RECOVERED_PRACTICAL_PASSAGES = [
  {
    paperId:'catti2-2022-11', section:'en-zh', number:1, title:'美国失业问题', topic:'就业与劳动力市场',
    sourceText:'The labor force is the total number of people (aged sixteen and older) employed and the unemployed. The unemployment rate is the percentage of the labor force unemployed but lacking work. Previously, the government gauged unemployment by the number of people who filed unemployment claims in a given month. However, because many people who are unemployed by the technical definition—that is, they are looking for work—do not qualify for unemployment benefits, the result was a serious undercounting of the unemployed. Now the United States relies on the monthly Current Population Survey from the Commerce Department, which provides a more comprehensive set of numbers based on household polls.\n\nNote that to be officially unemployed, a worker must be seeking employment. People without jobs who are not looking for work because they do not think any exists have, in effect, dropped out of the labor force and become discouraged workers. The labor force participation rate is the percentage of the total working-age population that is in the labor force.\n\nIn other words, the participation rate is the relationship between who is eligible to work and who actually is working. Variations in the rate may offer clues about social trends. In the mid-1990s, women entered the labor force in large numbers, probably the most significant economic shift of the post-war period. In the latter part of the decade, however, participation by women leveled off and dropped in some sectors. The reason is unclear and requires more research into changing relationships to work.\n\nEconomists talk about frictional, structural and cyclical unemployment. Frictional unemployment refers to people who have not had time to find a job because they are new to the labor force or between jobs. Structural unemployment results from deep economic changes; technology may make occupations obsolete. International markets can also replace higher-paid domestic workers with lower-paid foreign labor, as happened in important American industries such as steel and textiles.',
    referenceAnswer:'劳动力是16岁及以上就业人口和失业人口的总和，失业率则是劳动力中没有工作的人口所占的比重。此前，政府会根据一个月内申领失业救济金的人数来衡量失业率。然而，许多在技术性定义上已经失业、正在寻找工作的人并不具备领取救济金的资格，这使失业人数被严重低估。现在，美国依靠商务部每月开展的当期人口调查，根据家庭调查提供更全面的数据。\n\n需要注意的是，劳动者只有在寻找工作时才会被正式认定为失业人员。没有工作、又因认为不存在就业机会而不去找工作的人，实际上已经退出劳动力大军，成为丧志工人。劳动力参与率是处于劳动力市场中的人口占全部劳动年龄人口的百分比。\n\n换句话说，参与率反映有资格工作的人与实际在工作的人之间的关系，其变化可以为社会趋势提供线索。20世纪90年代中期，妇女大量加入劳动力队伍，或许是二战后最重大的经济转变；但90年代后期，妇女参与率趋于平稳并在一些行业下降。原因尚不明确，需要进一步研究工作关系的变化。\n\n经济学家谈到摩擦性、结构性和周期性失业。摩擦性失业是指刚进入劳动力市场或处于工作转换期、尚未找到工作的人。结构性失业源于经济深刻变化，技术进步可能使职业过时。国际市场也可能用低工资的外国劳动力取代本国高薪工人，美国钢铁、纺织等重要行业就出现过这种情况。',
    sourceUrls:['https://demo.ltpower.net/web/hydxswyy/news/show-5603.html'], referenceSource:'公开教学资料整理', sourceLabel:'机构考后整理 · 非官方原卷', contentVersion:'2022-11-public-recovery-v1'
  },
  {
    paperId:'catti2-2022-11', section:'en-zh', number:2, title:'新冠疫情的影响与合作抗疫', topic:'公共卫生与国际合作',
    sourceText:'A global health crisis of the magnitude we are experiencing has not struck the international community for over a century. In this unprecedented crisis, all countries and all areas of daily life are profoundly affected and in disarray. The sole weapon we currently possess against the virus is to constrain human contact as far as possible, and social distancing has become an important containment measure.\n\nAs a result, the world has come to a near standstill. From local transport to global supply chains, nothing has been spared. Activity in aviation has fallen by 90 percent and car sales have slumped by the same order of magnitude in some countries. The transport sector finds itself in an unprecedented situation, and its function of facilitating social interaction has come to a halt.\n\nAt the same time, transport must continue where moving people and goods is imperative. Doctors and nurses must get to work, hospitals must receive supplies, and confined citizens rely on provisions delivered to shops. International supply chains must move as seamlessly as possible to limit the inevitable economic impact.\n\nThe crisis also reminds us of three factors for recovery. First, we will overcome it more quickly if we work together across divides. Second, expertise and evidence-based decisions count; guesswork will not beat the virus or revive economies. Third, while dealing with the crisis, we must think about the future and plan for the post-pandemic age. The world will not be the same, but we have the knowledge and tools to shape change and must make the right choices.',
    referenceAnswer:'一个多世纪以来，国际社会从未遭遇过规模达到我们当前程度的全球健康危机。在这场史无前例的危机中，所有国家以及日常生活的方方面面都受到深刻影响并陷入混乱。目前，对抗病毒的唯一武器就是尽可能限制人与人之间的接触，保持社交距离已成为重要的遏制措施。\n\n因此，世界几乎陷入停滞。从地方交通到全球供应链，没有任何领域能够幸免。航空业活动减少了90%，一些国家的汽车销量也出现同等幅度的下滑。运输业正处于前所未有的境地，其促进社会交往的功能已经停止。\n\n与此同时，在人员和货物流动不可避免的地方，运输业仍必须运转。医生和护士必须能够上班，医院必须收到所需物资，居家隔离的居民依靠送到商店的生活用品。国际供应链必须尽可能顺畅，以把不可避免的经济影响控制在最低限度。\n\n这场危机还提醒我们，复苏需要三个因素。第一，跨越隔阂、共同合作能让我们更快克服危机。第二，专业知识和循证决策至关重要，仅凭猜测无法战胜病毒、重振经济。第三，在应对危机的同时，我们必须思考未来，为后疫情时代作出规划。世界将不再相同，但我们拥有塑造变化的知识和工具，必须作出正确选择。',
    sourceUrls:['https://demo.ltpower.net/web/hydxswyy/news/show-5603.html'], referenceSource:'公开教学资料整理', sourceLabel:'机构考后整理 · 非官方原卷', contentVersion:'2022-11-public-recovery-v1'
  },
  {
    paperId:'catti2-2022-11', section:'zh-en', number:1, title:'职业教育改革', topic:'教育与技能人才',
    sourceText:'职业教育是国民教育体系和人力资源开发的重要组成部分，是广大青年打开通往成功成才大门的重要途径。职业教育已为各行各业累计培养输送2亿多高素质劳动者。我国经济持续快速发展，职业教育功不可没。\n\n2019年1月，国务院颁发了《国家职业教育改革实施方案》，明确指出职业教育与普通教育是两种不同教育类型，具有同等重要地位。方案颁布以来，我国职业教育改革走上了快速发展的道路。\n\n在天津，本科层次职业教育发展取得改革突破。天津中德应用技术大学率先在一所学校内构建起中职高职衔接、职业教育与普通教育相互沟通的现代职业教育体系。首批599名职业教育本科生已经毕业，学生就业率远高于普通本科，就职领域集中于战略新兴产业和高端制造业。\n\n在西藏，职教扶贫工作取得新突破。西藏职业技术学院毕业生就业率从2018年的70%、2019年的89%跃升到2020年的95.17%，充分证明了职教扶贫政策的成功。\n\n但相对于高等教育，职业教育仍是我国教育领域的短板。我国技能人才已超过2亿人，占就业总量的26%；高技能人才仅有5000万人，占技能人才总量的28%。在一些人心中，职业教育依然低人一等，认可度和吸引力有待增强。因此必须提高技能人才待遇，畅通职业发展通道。',
    referenceAnswer:'Vocational education is an important component of the national education system and human-resource development, and an important pathway for young people to achieve success. It has trained and supplied more than 200 million highly qualified workers for all sectors. China’s sustained and rapid economic growth owes much to vocational education.\n\nIn January 2019, the State Council issued the Implementation Plan for the Reform of National Polytechnic Education, which stated that vocational and general education are two different types with equal importance. Since the plan was issued, vocational-education reform in China has developed rapidly.\n\nTianjin has made breakthroughs in undergraduate vocational education. Tianjin Sino-German University of Applied Sciences took the lead in building a modern system connecting secondary and higher vocational education and linking vocational and general education. Its first 599 undergraduate vocational students graduated with an employment rate far higher than that of regular undergraduates, mainly in strategic emerging industries and high-end manufacturing.\n\nTibet has made new progress in using vocational education to reduce poverty. The graduate employment rate at Tibet Vocational Technical College rose from 70 percent in 2018 to 89 percent in 2019 and 95.17 percent in 2020, demonstrating the policy’s success.\n\nCompared with higher education, vocational education remains a weak link. China has more than 200 million skilled workers, 26 percent of total employment, but only 50 million are highly skilled, 28 percent of skilled workers. Some still regard vocational education as inferior, so its recognition and appeal must be strengthened by improving skilled workers’ benefits and opening clearer career paths.',
    sourceUrls:['https://demo.ltpower.net/web/hydxswyy/news/show-5603.html'], referenceSource:'公开教学资料整理', sourceLabel:'机构考后整理 · 非官方原卷', contentVersion:'2022-11-public-recovery-v1'
  }
];
