export const SHORT_PARAGRAPH_REPAIRS={
paragraph_en_001:{
sourceText:'A school introduced a weekly discussion period so that students could question news reports and compare different sources. Teachers did not require one identical conclusion, but asked students to explain why they trusted particular evidence. The exercise gradually made classroom conversations more careful and respectful. To include quieter students, teachers allowed written comments before each discussion and made time for classmates to respond to them. They also kept a record of questions that could not yet be answered. In the following week, students returned with additional sources and considered whether their earlier judgments needed to change. The aim was to make uncertainty a starting point for inquiry rather than a reason to stop asking questions.',
referenceAnswer:'一所学校每周安排讨论课，让学生质疑新闻报道并比较不同来源。教师不要求所有人得出同一个结论，而要求学生说明为何信任某些证据。这项练习逐渐使课堂交流更加审慎，也更相互尊重。为让较少发言的学生参与，教师允许他们在每次讨论前提交书面意见，并留出时间让同学回应。教师还记录暂时无法回答的问题。下一周，学生带来更多资料，思考先前的判断是否需要改变。目的在于让不确定性成为探究的起点，而不是停止提问的理由。'},
paragraph_en_002:{
sourceText:'A neighborhood opened a small public garden on land that had been unused for years. Residents helped decide where to place trees, seats, and a play area. Because the garden was designed through local discussion, people were more willing to care for it after it opened. Volunteers organised a watering schedule, while the council remained responsible for checking equipment and repairing paths. Keeping these duties separate prevented enthusiasm from becoming a substitute for essential public maintenance. When a seat proved difficult for older visitors to use, residents reported the problem and a more suitable design was installed. The garden thus remained open to practical adjustment after the original construction work had ended.',
referenceAnswer:'一个社区在闲置多年的土地上开辟了一座小型公共花园。居民参与决定树木、座椅和游乐区的位置。由于花园通过当地讨论设计，人们在开放后也更愿意照料它。志愿者安排浇水轮值，地方议会仍负责检查设备和维修道路。明确区分这些职责，避免让居民的热情替代必要的公共维护。发现一张座椅不便于老年访客使用后，居民报告了问题，管理方换用了更合适的设计。因此，在最初施工结束后，花园仍能根据实际需要进行调整。'}
};

