import {shareTimerContract} from '../../components/training/timerModel';
import TrainingTimer,{useTrainingTimer} from '../../components/training/TrainingTimer';
import BackAction from '../../components/training/BackAction';
import PassageQuestions from '../../components/training/PassageQuestions';
import React,{useEffect,useRef,useState}from'react';import{useTrainingSessions}from'../../features/training/TrainingContext';import{VOCABULARY_EXERCISES,GRAMMAR_EXERCISES,READING_PASSAGES,CLOZE_PASSAGES}from'../../features/comprehensive/comprehensiveDataset';import'../../styles/global.css';
const labels={vocabulary:'词汇专项',grammar:'语法专项',reading:'阅读理解',cloze:'完形 / 语言运用'};
const makeSession=(e,answer,started)=>({exerciseId:e.id,exerciseType:'comprehensive',direction:e.direction||'en-zh',topic:e.topic,sourceText:e.sourceText||e.prompt,userAnswer:answer,referenceAnswer:e.answer||'',startedAt:new Date(started).toISOString(),submittedAt:new Date().toISOString(),durationMs:Math.max(0,Date.now()-started),recommendedDurationMs:e.estimatedMinutes?e.estimatedMinutes*60000:null,status:'completed',examLevel:e.examLevel,paperType:e.paperType,sectionType:e.sectionType,questionType:e.questionType,trainingMode:'comprehensive-practice',sourceType:e.sourceType,verificationStatus:e.verificationStatus,reviewStatus:e.reviewStatus,datasetVersion:e.datasetVersion});
function Objective({mode}){const{add}=useTrainingSessions();const items=mode==='vocabulary'?VOCABULARY_EXERCISES:GRAMMAR_EXERCISES;const[i,setI]=useState(0),[choice,setChoice]=useState(''),[submitted,setSubmitted]=useState(false),started=useRef(Date.now());const e=items[i];const timer=useTrainingTimer(e.id,3);useEffect(()=>{started.current=Date.now();setChoice('');setSubmitted(false)},[i,mode]);const submit=()=>{if(!choice)return;add({...makeSession(e,choice,started.current),durationMs:timer.activeDurationMs,startedAt:timer.startedAt,...timer.snapshot()});setSubmitted(true)};const correct=choice===e.answer;return <div className="training-page"><BackAction to="comprehensive-hub" label="综合能力" current={labels[mode]}/><div className="training-top"><div><p className="eyebrow">COMPREHENSIVE · {labels[mode]}</p><h2>{labels[mode]}</h2></div><span className="training-progress">{String(i+1).padStart(2,'0')} / {String(items.length).padStart(2,'0')}</span></div><TrainingTimer timer={timer} finished={submitted}/><div className="workspace-card"><div className="source-block"><p className="eyebrow">{e.topic} · {e.difficultyTier}</p><p className="source-text">{e.prompt}</p></div>{!submitted?<><div className="choice-list">{e.options.map(o=><label key={o}><input type="radio" name={e.id} value={o} checked={choice===o} onChange={()=>{if(!timer.started)timer.start('first-input');setChoice(o)}}/><span>{o}</span></label>)}</div><div className="training-actions"><button className="ui-button primary" disabled={!choice} onClick={submit}>提交答案</button></div></>:<div className={`feedback-panel result-${correct?'correct':'wrong'}`}><h3>{correct?'✓ 回答正确':'✕ 回答错误'}</h3><p>我的答案：{choice}</p><p>正确答案：{e.answer}</p><p>句子翻译：{e.sentenceTranslation||'—'}</p><p><strong>解析</strong> · {e.explanation}</p><div className="training-actions"><button className="ui-button" onClick={()=>setI(Math.max(0,i-1))} disabled={i===0}>上一题</button><button className="ui-button primary" onClick={()=>setI((i+1)%items.length)}>下一题 →</button></div></div>}</div></div>}
function Passage({mode}){
 const {add}=useTrainingSessions();const pool=mode==='reading'?READING_PASSAGES:CLOZE_PASSAGES;
 const [i,setI]=useState(0),[answers,setAnswers]=useState({}),[submitted,setSubmitted]=useState(false);const p=pool[i];
 const timer=useTrainingTimer(p.id,mode==='reading'?25:20);const questions=mode==='reading'?p.questions:p.blanks;
 useEffect(()=>{setAnswers({});setSubmitted(false)},[p.id]);
 const submit=()=>{if(submitted||questions.some(q=>!answers[q.id]))return;timer.finish();const contract=timer.snapshot(),now=new Date().toISOString();questions.forEach((q,n)=>add({...makeSession({...p,...q,sourceText:p.sourceText||p.passage,topic:p.topic,questionType:mode},answers[q.id],Date.parse(timer.startedAt)),submittedAt:now,...shareTimerContract(contract,questions.length,n)}));setSubmitted(true)};
 return <div className="training-page split-workspace"><BackAction to="comprehensive-hub" label="综合能力" current={labels[mode]}/><div className="training-top"><h2>{labels[mode]}</h2><span>{i+1} / {pool.length}</span></div><TrainingTimer timer={timer} finished={submitted}/><PassageQuestions passage={p.passage||p.sourceText} questions={questions} answers={answers} onAnswer={(id,value)=>{if(!timer.started)timer.start('first-input');setAnswers(a=>({...a,[id]:value}))}} submitted={submitted} mode={mode}/><div className="training-actions"><button className="ui-button" disabled={!i} onClick={()=>setI(i-1)}>上一篇</button><button className="ui-button primary" onClick={submit} disabled={submitted||questions.some(q=>!answers[q.id])}>提交整篇</button><button className="ui-button" disabled={i===pool.length-1} onClick={()=>setI(i+1)}>下一篇</button></div></div>
}
export default function ComprehensiveTrainingPage({mode}){if(mode==='reading'||mode==='cloze')return <Passage mode={mode}/>;return <Objective mode={mode||'vocabulary'}/>}


