import React,{useMemo,useState}from'react';
import{PAST_PAPERS,validatePastPapers}from'../../features/questionBank/pastPaperDataset';
import{SENTENCE_EXERCISES}from'../../features/exercises/sentenceDataset';
import{PARAGRAPH_EXERCISES}from'../../features/questionBank/paragraphDataset';
import{COMPREHENSIVE_EXERCISES}from'../../features/comprehensive/comprehensiveDataset';import{EXTENDED_EXERCISES}from'../../features/translation/extendedDataset';import{CATTI_PRACTICE_SETS}from'../../features/translation/practiceSets';
import'../../styles/global.css';
const labels={verified:'已核验',pending:'待核验',questionable:'有疑问'};
const nav=id=>window.dispatchEvent(new CustomEvent('catti:navigate',{detail:id}));
export default function QuestionBankPage(){
 const[category,setCategory]=useState('specialized'),[year,setYear]=useState('all'),[direction,setDirection]=useState('all'),[status,setStatus]=useState('all'),[query,setQuery]=useState('');
 const years=[...new Set(PAST_PAPERS.map(p=>p.year))].sort((a,b)=>b.localeCompare(a));
 const rows=useMemo(()=>PAST_PAPERS.filter(p=>(year==='all'||p.year===year)&&(direction==='all'||p.direction===direction)&&(status==='all'||p.verificationStatus===status)&&(!query.trim()||[p.title,p.topic,p.sourceText].join(' ').toLowerCase().includes(query.trim().toLowerCase()))),[year,direction,status,query]);
 const clear=()=>{setYear('all');setDirection('all');setStatus('all');setQuery('')};
 return <div className="question-page"><div className="page-hero"><div><p className="eyebrow">QUESTION BANK</p><h2>训练题库与内容样本</h2><p>区分专项练习、综合能力与来源明确的真题内容。</p></div></div>
  <div className="question-filters category-filters">{[['specialized','专项练习'],['comprehensive','综合能力'],['papers','题库样本 / Past Papers']].map(([v,l])=><button type="button" className={`ui-button ${category===v?'primary':''}`} onClick={()=>setCategory(v)} key={v}>{l}</button>)}</div>
  {category==='specialized'&&<div className="paper-list"><article className="paper-row"><div className="paper-info"><h3>Sentence Practice</h3><p>句子专项 · {SENTENCE_EXERCISES.length} 条 · 中译英 / 英译汉</p></div><button className="ui-button" onClick={()=>nav('sentence')}>进入训练</button></article><article className="paper-row"><div className="paper-info"><h3>Paragraph Practice</h3><p>篇章专项 · {PARAGRAPH_EXERCISES.length} 条 · 中译英 / 英译汉</p></div><button className="ui-button" onClick={()=>nav('paragraph')}>进入训练</button></article><article className="paper-row"><div className="paper-info"><h3>Extended Passage</h3><p>高负荷篇章专项 · {EXTENDED_EXERCISES.length} 篇 · 中译英 / 英译汉</p></div><button className="ui-button" disabled>扩展训练入口整理中</button></article><article className="paper-row"><div className="paper-info"><h3>CATTI Practice Set</h3><p>完整实务训练 · {CATTI_PRACTICE_SETS.length} 套 · 预计 180 min</p><small>内置 practice set，不是官方历年真题。</small></div><button className="ui-button" disabled>完整考试 workspace 即将开放</button></article></div>}
  {category==='comprehensive'&&<div className="paper-list"><article className="paper-row"><div className="paper-info"><h3>笔译综合能力专项训练</h3><p>词汇、语法、阅读与语言运用 · {COMPREHENSIVE_EXERCISES.length} 条 practice</p><small>非官方真题，供备考训练使用。</small></div><button className="ui-button" onClick={()=>nav('comprehensive')}>开始训练</button></article></div>}
  {category==='papers'&&<><div className="question-filters"><select aria-label="年份" value={year} onChange={e=>setYear(e.target.value)}><option value="all">全部年份</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select><select aria-label="方向" value={direction} onChange={e=>setDirection(e.target.value)}><option value="all">全部方向</option><option value="zh-en">中译英</option><option value="en-zh">英译汉</option></select><select aria-label="核验状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option><option value="verified">已核验</option><option value="pending">待核验</option><option value="questionable">有疑问</option></select><input aria-label="搜索" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索标题、主题或原文..."/><button type="button" className="ui-button" onClick={clear}>清除筛选</button></div><div className="paper-list">{rows.length?rows.map(p=><article className="paper-row" key={p.id}><span className="paper-year">{p.year} / {p.session}</span><div className="paper-info"><h3>{p.title}</h3><p>CATTI 英语二级笔译 · {p.direction==='zh-en'?'中译英':'英译汉'} · {p.topic}</p><small>{p.source}</small></div><span className="status-pill">{labels[p.verificationStatus]}</span><button type="button" className="ui-button" disabled>真题练习即将开放</button></article>):<div className="empty-panel"><p>没有找到符合条件的真题。</p><button type="button" className="ui-button" onClick={clear}>清除筛选</button></div>}</div>{!validatePastPapers()&&<p role="alert">题库数据校验失败</p>}</>}
 </div>;
}

