import React,{useState} from 'react';
import {FULL_PRACTICE_SETS} from '../../features/translation/fullPracticeSets';
import {EXAM_PASSAGES} from '../../features/translation/examPassageDataset';
import {useTrainingSessions} from '../../features/training/TrainingContext';
import {readStorage,writeStorage,STORAGE_KEYS} from '../../storage/storageAdapter';
import BackAction from '../../components/training/BackAction';
import TrainingTimer,{useTrainingTimer} from '../../components/training/TrainingTimer';
const KEY=STORAGE_KEYS.fullPracticeDrafts;
export default function FullPracticePage(){const [selected,setSelected]=useState(null);return selected?<FullWorkspace key={selected.id} set={selected} onBack={()=>setSelected(null)}/>:<div className="training-page"><BackAction to="simulation" label="整套模拟" current="笔译实务"/><h2>笔译实务整套模拟</h2><p>CATTI Lab 自建模拟卷 · 每套两个方向各两篇 · 180 min</p><div className="hub-list">{FULL_PRACTICE_SETS.map(s=><button key={s.id} className="hub-row" onClick={()=>setSelected(s)}><span><b>{s.title}</b><small>{s.difficultyTier||'CATTI Standard'} · 4 Passages</small></span><strong>开始 →</strong></button>)}</div></div>}
function FullWorkspace({set,onBack}){
 const {add}=useTrainingSessions();const ids=Object.values(set.directions).flat(),passages=ids.map(id=>EXAM_PASSAGES.find(p=>p.id===id));
 const [index,setIndex]=useState(0),[answers,setAnswers]=useState(()=>readStorage(KEY,{})),[saved,setSaved]=useState(false),[submitted,setSubmitted]=useState(false);const e=passages[index],timer=useTrainingTimer(set.id,180,e.id);
 const update=value=>{const next={...answers,[`${set.id}:${e.id}`]:value};setSaved(false);setAnswers(next);writeStorage(KEY,next)};
 const finish=()=>{if(submitted)return;timer.finish();const now=new Date().toISOString(),durations=timer.segmentDurations(),contract=timer.snapshot();passages.forEach((p,i)=>add({exerciseId:p.id,exerciseType:'full-practice',trainingMode:'full-practice',paperId:set.id,direction:p.direction,topic:p.topic,sourceText:p.sourceText,userAnswer:answers[`${set.id}:${p.id}`]||'',referenceAnswer:p.referenceAnswer,startedAt:timer.startedAt,submittedAt:now,...contract,durationMs:durations[p.id]||0,activeDurationMs:durations[p.id]||0,groupActiveDurationMs:contract.activeDurationMs,status:'completed',sourceType:'simulated',source:'CATTI Lab 自建模拟卷',contentVersion:p.contentVersion}));setSubmitted(true)};
 return <div className="training-page"><BackAction label="笔译实务" current={set.title} onClick={onBack}/><h2>{set.title}</h2><TrainingTimer timer={timer} finished={submitted}/><div className="paragraph-tabs">{passages.map((p,i)=><button key={p.id} className={i===index?'active':''} onClick={()=>setIndex(i)}>{p.direction==='zh-en'?'中译英':'英译汉'} {i%2+1}{answers[`${set.id}:${p.id}`]?' · 已填写':''}</button>)}</div><div className="translation-workspace"><section className="translation-source"><p className="eyebrow">{e.topic}</p><p className="source-text">{e.sourceText}</p></section><section className="translation-editor-panel"><label className="editor-label" htmlFor="full-practice-answer">你的译文</label><textarea id="full-practice-answer" className="translation-editor" value={answers[`${set.id}:${e.id}`]||''} onChange={ev=>{if(ev.target.value&&!timer.started)timer.start('first-input');update(ev.target.value)}} readOnly={submitted}/>{submitted&&<section className="feedback-panel"><p>整套四篇已保存到学习记录。</p><h3>参考译文</h3><p>{e.referenceAnswer}</p></section>}<div className="training-actions"><button className="ui-button" onClick={()=>{writeStorage(KEY,answers);setSaved(true)}}>保存草稿</button><button className="ui-button" disabled={index===0} onClick={()=>setIndex(index-1)}>上一篇</button><button className="ui-button" disabled={index===3} onClick={()=>setIndex(index+1)}>下一篇</button><button className="ui-button primary" disabled={submitted||passages.some(p=>!answers[`${set.id}:${p.id}`]?.trim())} onClick={finish}>提交整套训练</button></div>{saved&&<p className="source-note" role="status">草稿已保存</p>}<p className="source-note">草稿自动保存。时间到后可继续作答，不会强制交卷。</p></section></div></div>
}
