export const REBUILD_SENTENCES=[
['zh-en','财政与问责','专项资金结余并不必然说明项目缺乏需求，因为那些最需要援助、却无法提前垫付费用的小型机构，可能恰恰由于现行拨款程序要求先支出后报销而无法申请，从而使未被满足的需求在财务报表中表现为资金过剩。','An unspent balance in earmarked funds does not necessarily indicate a lack of demand: small organisations most in need of assistance but unable to advance the costs may be prevented from applying precisely because the disbursement procedure requires them to spend first and claim reimbursement later, making unmet need appear in financial statements as surplus funding.','报销时序与结余的因果反转；结余不可直接解释为无需求。'],
['zh-en','文化与语言','方言词汇进入博物馆的过程，如果只是由外来研究者挑选最具特色的表达，再用标准语提供看似准确的释义，就可能把仍随生活情境变化的交流方式固定成供人观看的标本，而让使用者自己解释词义和使用场合的权利再次被忽略。','If dialect words enter a museum solely through outsiders selecting distinctive expressions and supplying apparently precise definitions in the standard language, the process may turn a mode of communication that continues to change with lived circumstances into a specimen for display, once again overlooking speakers’ right to explain its meanings and contexts of use.','条件作用于收录过程；标本隐喻；使用者权利与被动重组。'],
['zh-en','科学与证据','研究团队未能重复一项广受关注的实验，并不足以证明原结论出于伪造，但如果导致差异的条件始终无法说清，那么仅仅援引首次研究者的声誉，也不能成为继续把该结论当作已获证实的事实写入教材的理由。','A research team’s failure to replicate a widely discussed experiment does not suffice to prove that its original conclusion was fabricated; but if the conditions responsible for the discrepancy remain unexplained, invoking the original researchers’ reputation alone cannot justify continuing to present that conclusion in textbooks as an established fact.','未复现不等于伪造；双重不足推论；条件辖域和主语转换。'],
['zh-en','国际投资','在决定是否延长投资优惠时，政府不仅要比较企业承诺创造的就业与实际新增岗位，还应扣除那些即使没有优惠也会出现的增长，否则，一项看似成功吸引投资的政策，就可能只是以公共收入补贴原本就会发生的商业活动。','When deciding whether to extend investment incentives, a government should compare promised jobs with actual additions and also subtract the growth that would have occurred without the incentives; otherwise, a policy that appears successful in attracting investment may merely subsidise, out of public revenue, commercial activity that would have taken place anyway.','没有优惠的反事实基线；扣除对象；财政收入转介词短语。'],
['zh-en','历史与档案','一封私人书信之所以能够修正我们对某次谈判的理解，并不是因为私人叙述天然比官方记录真实，而是因为它揭示了公开声明中被省略的选择空间，使研究者得以区分当事人后来声称别无选择的立场与他们当时实际考虑过的方案。','A private letter can revise our understanding of a negotiation not because private accounts are inherently truer than official records, but because it reveals alternatives omitted from public statements, enabling researchers to distinguish the participants’ later claim that they had no choice from the options they actually considered at the time.','不是因为而是因为；later/at the time对照；别无选择并非客观事实。'],
['zh-en','基础设施','即使收费公路的经营合同已经把车流不足的风险交给私人投资者，只要政府仍被普遍认为会在项目破产时出面救助，这种账面上的风险转移就未必能够约束过度借贷，反而可能使最终由公众承担的责任更加难以察觉。','Even if a toll-road concession formally assigns the risk of insufficient traffic to private investors, that transfer on paper may fail to restrain excessive borrowing so long as the government is widely expected to intervene in bankruptcy, and may instead make the liabilities ultimately borne by the public harder to detect.','法律风险转移与隐性担保；even if/so long as层级；liabilities准确义。'],
['en-zh','金融监管',`Had supervisors distinguished losses arising from an unforeseeable interruption of payments from those attributable to risks that lenders had knowingly concentrated in a single industry, the guarantee might have preserved essential credit without creating the expectation that private gains could be retained while the consequences of inadequate scrutiny would, whenever sufficiently large institutions were involved, ultimately be transferred to the public.`,`如果监管者当初区分了不可预见的支付中断造成的损失，与贷款机构明知而将风险集中于单一行业所造成的损失，这项担保或许既能维持必要信贷，又不至于让人预期私人可以保留收益，而审查不足的后果，只要涉及规模足够大的机构，最终便会转嫁给公众。`,'Had反事实；those指损失；whenever限定责任转移；may避免变成确定结果。'],
['en-zh','法庭与证据',`The absence of a contemporaneous record, although it may weaken a claim that a particular undertaking was formally agreed, cannot by itself establish that no assurance was given, especially where the party now demanding documentary proof controlled the procedures through which commitments were recorded and had previously encouraged the other party to rely on understandings that were deliberately left outside the written contract.`,`缺少同期记录，虽然可能削弱关于某项承诺已经正式达成的主张，却不能单凭这一点就认定从未作出保证；尤其是现在要求书面证据的一方，当初掌控了承诺的记录程序，并且曾鼓励另一方依赖那些被有意排除在书面合同之外的共识时，更是如此。`,'although让步；undertaking承诺而非事业；where情境与that双层关系从句。'],
['en-zh','科研评价',`What makes the revised assessment less vulnerable to manipulation is not the addition of another numerical target, which researchers might learn to satisfy without improving the reliability of their work, but the requirement that evaluators explain how the evidence supports their judgment and identify the circumstances in which an apparently disappointing result should count as a valuable correction to an influential but inadequately tested assumption.`,`使修订后的评价更不易被操纵的，并不是再增加一个数字目标——研究者可能学会达标，却不提高研究的可靠性——而是要求评价者解释证据如何支持其判断，并说明在什么情况下，一个看似令人失望的结果应被视为对某种影响广泛但检验不足的假设所作的有价值纠正。`,'what主语从句；not…but范围；非限定which与in which嵌套；count as评价。'],
['en-zh','商业竞争',`A platform’s assurance that all sellers face identical contractual terms offers little evidence of equal treatment if a payment delay that a large retailer can absorb forces a smaller supplier to borrow at punitive rates, particularly when the platform can change that delay without notice while continuing to advertise the resulting reduction in its own financing costs as proof of greater operational efficiency.`,`如果大型零售商能够承受的付款延迟，却迫使小供应商以苛刻利率借款，那么平台声称所有卖方适用相同合同条款，几乎不足以证明待遇平等；尤其是平台可以不加通知地改变付款期限，又继续把由此降低自身融资成本宣传为运营效率提高的证据时，更是如此。`,'equal terms/equal treatment不同；that对照限制；own与resulting的指向。'],
['en-zh','国际组织',`Whether an international agreement can survive a change of government depends less on the ceremonial force of the original declaration than on whether its procedures allow participants to challenge the distribution of costs without abandoning cooperation altogether, a distinction easily overlooked when unanimous endorsement is treated as evidence that the competing interests which the agreement was designed to reconcile have somehow ceased to exist.`,`一项国际协议能否经受政府更迭，更多取决于其程序是否容许参与方质疑成本分配而不彻底放弃合作，而非最初声明的仪式性力量；当人们把一致赞同当成证据，认为协议旨在调和的竞争利益竟已不复存在时，这一区分便容易被忽略。`,'whether并列；less…than比较；a distinction同位回指；which长距离修饰。'],
['en-zh','科学史',`To describe a discovery as inevitable once the relevant instruments became available is to overlook not only the judgments through which ambiguous observations were made intelligible, but also the institutional arrangements that enabled some investigators to pursue uncertain findings while requiring others, whose contributions subsequently disappeared from the published account, to perform the repetitive labour on which the celebrated interpretation ultimately depended.`,`把一项发现描述为相关仪器出现后便不可避免，就不仅忽略了使模糊观察变得可理解的判断，也忽略了相应的制度安排：这些安排使一些研究者得以追索不确定的发现，却要求另一些人从事重复劳动，而备受赞誉的解释最终正有赖于这些劳动，后者的贡献却随后从公开叙述中消失了。`,'To…is to批评结构；whose插入回指others；on which介词与劳动依赖。']
];
