import {reviewedSeed} from '../content/seedReview.js';
const rows=[
['zh-en','公共政策','尽管试点地区的平均办事时间明显缩短，但若不区分网上办理与窗口办理的申请人，就无法判断效率提升是否同样惠及那些最难使用数字服务的人。','Although average processing times fell substantially in the pilot areas, it is impossible to determine whether the efficiency gains also benefited those least able to use digital services without distinguishing online applicants from those applying in person.','让步从句、若不……就无法……及 those least able 的限制共同界定结论。'],
['zh-en','能源转型','对那些尚未收回传统设备投资的中小企业而言，转型能否推进，不仅取决于新技术的价格，还取决于融资期限是否足以覆盖设备更换带来的现金流压力。','For small and medium-sized enterprises that have yet to recover their investment in conventional equipment, progress in the transition depends not only on the price of new technology but also on whether financing terms are long enough to accommodate the cash-flow pressures of replacing equipment.','前置对象、尚未状态、融资期限与现金流之间的条件关系。'],
['zh-en','教育','如果评价制度只奖励能够迅速量化的成果，那么那些需要长期观察才能显现的教学改进，即使真正有利于学生，也可能在资源分配中被低估。','If an evaluation system rewards only outcomes that can be quantified quickly, improvements in teaching that become apparent only through long-term observation may be undervalued in resource allocation, even when they genuinely benefit students.','两个 only 限定不同对象，even when 让步不能变成因果。'],
['zh-en','科研','研究者应当公布未能支持原有假设的结果，因为只让成功案例进入公共讨论，既会夸大一种方法的可靠性，也会使后来者重复本可避免的错误。','Researchers should publish results that fail to support their original hypotheses, because allowing only successful cases into public discussion both exaggerates the reliability of a method and leads others to repeat mistakes that could have been avoided.','未支持并非证明错误；两个后果与过去反事实 could have been avoided。'],
['zh-en','国际合作','双方真正需要明确的，并非文件中某个词在字典里的含义，而是在具体执行条件下，谁有权作出决定、谁承担成本，以及发生分歧时应依据什么程序协商。','What the two sides need to clarify is not the dictionary meaning of a word in the document, but who is authorised to decide under the actual conditions of implementation, who bears the costs, and what procedures should govern negotiations when disagreements arise.','主语从句与三项嵌套疑问并列，需保持权限/成本/程序独立。'],
['zh-en','文化','对一项传统技艺的保护，若仅限于保存成品而忽视传承人赖以生活的社会关系，就可能在留下精美展品的同时，失去使这门技艺继续发展的条件。','If the protection of a traditional craft is confined to preserving finished objects while neglecting the social relationships on which its practitioners depend, it may retain exquisite exhibits yet lose the conditions that enable the craft to develop further.','若仅限于的条件包住保存与忽视对比，同时保留成功与损失并存。'],
['zh-en','公共预算','预算公开只有在居民能够理解各项支出的用途、比较不同方案的代价，并在决定尚可调整时提出意见的情况下，才可能从信息展示转化为有效问责。','Budget disclosure can move beyond displaying information to enabling effective accountability only when residents can understand the purpose of expenditure, compare the costs of alternative proposals, and comment while decisions can still be changed.','只有才为必要而非充分条件，尚可调整的时间窗口不可漏译。'],
['zh-en','平台经济','一家平台声称其规则适用于所有商户，并不意味着这些规则造成的负担同样公平，因为规模较小、融资渠道较少的经营者往往更难承受突然变化的付款周期。','A platform’s claim that its rules apply to all merchants does not mean that the burdens they impose are equally fair, since smaller businesses with fewer financing options often find sudden changes in payment schedules harder to bear.','主语是声称而非已核实事实，形式普遍与实际负担对比。'],
['zh-en','生态保护','即便某项修复工程确实提高了当地的物种数量，如果这一变化是以相邻地区的栖息地退化为代价，也不能据此认定整个生态系统已经改善。','Even if a restoration project has genuinely increased the number of species locally, this alone does not establish an improvement in the ecosystem as a whole if the gain has come at the expense of habitat degradation in neighbouring areas.','双层条件限定推断范围，局部增益不等于整体改善。'],
['zh-en','档案','那些没有留下正式记录的经历，不应仅仅因为难以纳入既有分类就被排除在城市记忆之外，但将其纳入档案也不意味着可以放弃对叙述来源和形成过程的审查。','Experiences that left no formal records should not be excluded from a city’s memory merely because they are difficult to fit into existing categories, but incorporating them into an archive does not justify abandoning scrutiny of the sources of accounts and how they were produced.','not merely because 与 does not justify 双重限定，包容不能替代证据审查。'],
['en-zh','金融','Had the guarantee been limited to losses that lenders could neither anticipate nor reasonably prevent, it might have protected essential credit without weakening the incentive to assess borrowers carefully.','如果担保当初仅限于贷款机构既无法预见、也无法合理防止的损失，它或许能够在保障必要信贷的同时，不削弱审慎评估借款人的激励。','Had 引导过去反事实，neither/nor 双重范围与 might 的不确定性。'],
['en-zh','技术治理','The fact that an algorithm performs well on cases resembling those in its training data says less about its suitability for a new population than a headline accuracy figure might suggest.','算法在与训练数据相似的案例上表现良好，这一事实对其是否适用于新群体的说明力，并没有醒目的准确率数字可能给人的印象那么强。','says less...than 比较说明力，不是说算法对所有人都失效。'],
['en-zh','教育','What the evaluation failed to capture was not a lack of progress, but the extent to which teachers had redirected effort towards outcomes that the chosen indicators could not register.','评价未能反映的并非没有进步，而是教师在多大程度上将精力转向了那些既定指标无法记录的成果。','主语及表语从句，not...but 的否定范围避免译成教师没有进步。'],
['en-zh','环境','Unless the cost of maintaining restored habitats is included from the outset, a project celebrated for its initial impact may leave local authorities with obligations they have neither the funds nor the staff to meet.','除非一开始就把维护修复后栖息地的费用计入，否则一项因初期成效而备受赞誉的工程，可能给地方政府留下既无资金也无人手履行的义务。','Unless 的必要条件与 neither funds nor staff，定语 celebrated 保留初期评价。'],
['en-zh','科研','An explanation that fits every observation after the event is not necessarily more useful than a narrower claim whose limits are stated in advance and whose predictions can be tested independently.','一种在事后能够解释每项观察结果的说法，并不一定比一种范围更窄、事先明确局限且预测可被独立检验的主张更有用。','not necessarily 与 more useful 比较，whose 两项检验条件保持并列。'],
['en-zh','劳动','Workers whose schedules change with little notice may value predictable hours more than a nominal increase in pay, particularly where childcare cannot be rearranged at the same short notice.','对于工作安排在很短通知期内就发生变化的劳动者而言，可预测的工时可能比名义上的加薪更重要，尤其是在托育安排无法同样迅速调整的情况下。','may value 不泛化为所有劳动者；particularly where 嵌套情境限定。'],
['en-zh','公共数据','To disclose a dataset without documenting the decisions that shaped it is to invite users to mistake an administrative record for a complete account of the population it purports to describe.','公布一套数据却不说明塑造它的各项决定，无异于让使用者把行政记录误当成对其声称描述的人群的完整记录。','To...is to 不定式主语/表语，purports 保留声称而非认可完整性。'],
['en-zh','城市发展','A transport investment can improve the network as a whole while making some journeys harder, which is why aggregate gains should not be used to dismiss objections from passengers whose connections disappear.','一项交通投资可能改善整个网络，却使某些出行更加困难；因此，不应以总体收益为由，否定那些失去换乘衔接的乘客提出的异议。','while 同时成立的对比，which 指整项前句而非单一名词。'],
['en-zh','国际贸易','The apparent diversification of suppliers offers little protection if firms listed under different names ultimately depend on the same processing facility, a connection that conventional contract reviews may overlook.','如果登记名称不同的企业最终依赖同一座加工设施，那么供应商表面上的多元化几乎不能提供保护，而传统合同审查可能忽略这种联系。','if 限定结论及同位补充，ultimate dependence 不等于合同主体相同。'],
['en-zh','科学传播','Acknowledging uncertainty does not require treating every interpretation as equally plausible; it requires explaining which conclusions the evidence supports, which remain tentative, and what would justify revising them.','承认不确定性并不要求把每种解释都视为同样可信，而是要求说明证据支持哪些结论、哪些仍属暂定，以及什么理由足以支持修正这些结论。','分号前后否定/肯定对照，三项从句须保留证据分级及修正条件。']
];
export const NEW_SENTENCE_SEEDS=rows.map(([direction,topic,sourceText,referenceAnswer,structure],i)=>reviewedSeed({id:'roundb_sentence_'+direction.replace('-','_')+'_'+String(i%10+1).padStart(3,'0'),type:'sentence',contentType:'sentence',direction,topic,sourceText,referenceAnswer,hints:[structure,'先保留逻辑与限定，再调整译文语序。'],estimatedMinutes:5,contentVersion:1,datasetVersion:3},{tier:'catti-standard',evidence:{lexicalComplexity:'领域：'+topic+'；本句的抽象名词与正式语域需结合具体谓词处理。',syntacticComplexity:structure,inferenceDemand:'审查句内条件是否足以推出主句，保留 may/可能和否定限制。',discourseComplexity:'单句内部存在对比或条件层次，不能拆成彼此无关的陈述。',domainKnowledge:'原句已提供'+topic+'背景，不要求额外增加数据或观点。',translationChallenges:'参考逐项对应题目主干、修饰对象及结论范围，避免条件转换失真。'},notes:'原文—参考逐分句核对：'+structure}));

