import {REBUILD_SENTENCES} from './rebuildSentences.js';
import {rebuildTranslation} from '../content/rebuildTranslation.js';
import {isPublishedContent} from '../content/contentValidation.js';
import {NEW_SENTENCE_SEEDS} from './reviewedSentenceSeeds.js';
import {reviewedSeed,quarantine} from '../content/seedReview.js';
import {normalizeExercise} from './exerciseSchema.js';
import {difficultyForIndex} from '../content/contentDifficulty.js';
const zh=[['城市更新不只是建筑空间的变化，也关乎人们如何在熟悉的地方继续生活。','Urban renewal is not merely a change in architectural space; it is also about how people continue to live in familiar places.','社会发展'],['公共文化空间只有真正向不同年龄的人开放，才能发挥连接社区的作用。','Public cultural spaces can connect communities only when they are genuinely open to people of different ages.','公共文化'],['推动科技创新时，制度设计应当为试验和修正保留足够空间。','When promoting technological innovation, institutional design should leave enough room for experimentation and correction.','科技创新'],['教育的价值不仅在于传授知识，也在于培养独立判断的能力。','The value of education lies not only in imparting knowledge but also in cultivating independent judgment.','教育'],['绿色转型需要长期规划，也需要公众理解并参与日常行动。','The green transition requires long-term planning as well as public understanding and participation in everyday action.','环境与可持续发展'],['稳定的融资渠道能够帮助中小企业把短期订单转化为长期能力。','Stable financing channels can help small and medium-sized enterprises turn short-term orders into lasting capacity.','经济发展'],['有效的国际交流始于倾听，而不是急于表达自己的立场。','Effective international exchange begins with listening rather than rushing to express one’s own position.','国际交流'],['城市治理既要追求办事效率，也要回应居民对公平和温度的期待。','Urban governance must pursue administrative efficiency while responding to residents’ expectations of fairness and human consideration.','城市治理'],['数字服务带来便利，但设计者仍须考虑不会使用智能设备的人。','Digital services bring convenience, but designers must still consider people who cannot use smart devices.','数字社会'],['传统文化只有进入当代生活，才可能在年轻人中获得新的生命力。','Traditional culture can gain new vitality among young people only when it enters contemporary life.','传统文化']];
const en=[['Every translation depends on a careful reading of context before any sentence is rewritten.','每一次翻译都取决于在改写句子之前对语境的仔细阅读。','翻译方法'],['A public policy may look efficient on paper but produce unequal results in practice.','一项公共政策在纸面上可能看似高效，但在实践中却产生不平等的结果。','公共政策'],['Researchers need to explain uncertainty clearly when presenting a promising discovery.','研究人员在介绍一项有前景的发现时，需要清楚地解释其中的不确定性。','科技创新'],['Schools should give students opportunities to question information instead of memorizing every answer.','学校应给学生质疑信息的机会，而不是要求他们记住每一个答案。','教育'],['Sustainable development requires economic decisions to account for their environmental costs.','可持续发展要求经济决策考虑其环境成本。','环境与可持续发展'],['Small businesses are more willing to invest when market rules are predictable.','当市场规则具有可预见性时，小企业更愿意进行投资。','经济发展'],['International cooperation becomes stronger when local experience is treated as valuable evidence.','当地方经验被视为有价值的证据时，国际合作会更加稳固。','国际交流'],['Residents are more likely to support urban projects when they can see how decisions are made.','当居民能够了解决策如何作出时，他们更有可能支持城市项目。','城市治理'],['Digital platforms should make important rules understandable to ordinary users.','数字平台应让普通用户能够理解重要规则。','数字社会'],['Museums can preserve memory while also inviting people to reinterpret the past.','博物馆既可以保存记忆，也可以邀请人们重新理解过去。','传统文化']];
const topics=['economy','technology','AI','environment','energy','education','culture','society','urban development','international affairs','business','science','public policy','agriculture','innovation','history'];
const make=(row,direction,i)=>normalizeExercise({id:`sentence_practice_${direction}_${String(i+1).padStart(3,'0')}`,type:'sentence',direction,topic:row[2],sourceText:row[0],referenceAnswer:row[1],hints:['先判断句子主干，再处理修饰关系。','注意保持语气、逻辑关系和正式语域。'],difficultyLevel:difficultyForIndex(i,50),difficultyReason:i<5?'clear basic structure for foundation practice':i<15?'formal register and sentence restructuring':'nominalization, semantic ambiguity and register control',skillTags:['sentence restructuring','formal register','logic'],estimatedMinutes:i<10?3:4,sourceType:'practice',verificationStatus:'pending',reviewStatus:'approved',contentVersion:1,datasetVersion:2});
const extraZh=Array.from({length:40},(_,i)=>{const topic=topics[i%topics.length];return [`在${topic}的第${i+1}个案例中，公共议题需要在效率、成本与公平之间作出具体取舍，决策者不能只依赖单一指标。`,`This public issue requires a concrete balance among efficiency, cost, and fairness; decision-makers cannot rely on a single indicator.` ,topic]});
const extraEn=Array.from({length:40},(_,i)=>{const topic=topics[(i+4)%topics.length];return [`In the ${topic} case ${i+1}, a careful policy review should distinguish a temporary setback from a structural problem, because the remedy depends on the evidence available.`,`谨慎的政策评估应区分暂时性挫折与结构性问题，因为补救方式取决于现有证据。`,topic]});
const LEGACY_SENTENCES=[...zh.map((x,i)=>make(x,'zh-en',i)),...en.map((x,i)=>make(x,'en-zh',i)),...extraZh.map((x,i)=>make(x,'zh-en',i+10)),...extraEn.map((x,i)=>make(x,'en-zh',i+10))];

const PRE_REBUILD_SENTENCES=LEGACY_SENTENCES.map(x=>Number(x.id.slice(-3))<=10?reviewedSeed({...x,contentType:'sentence'},{notes:'原句、逻辑、否定与参考逐句核对；仅定为基础专项，不宣称 CATTI Standard。'}):quarantine({...x,contentType:'sentence'},'仅替换领域/编号的模板题；译文遗漏领域与编号。')).concat(NEW_SENTENCE_SEEDS);
export const ALL_SENTENCE_EXERCISES=[...PRE_REBUILD_SENTENCES.map(x=>x.contentStatus==='published'?quarantine({...x,deprecated:true},'训练规格重建：旧短句退出当前池，历史快照不变。'):x),...REBUILD_SENTENCES.map((x,i)=>rebuildTranslation(x,i,'sentence'))];
export const SENTENCE_EXERCISES=ALL_SENTENCE_EXERCISES.filter(isPublishedContent);
